export const NAMES = [
  { en: "John Doe", ar: "جون دو", ja: "ジョン・ドー", fr: "Jean Doe" },
  {
    en: "Alice Smith",
    ar: "أليس سميث",
    ja: "アリス・スミス",
    fr: "Alice Smith",
  },
  {
    en: "Bob Johnson",
    ar: "بوب جونسون",
    ja: "ボブ・ジョンソン",
    fr: "Bob Johnson",
  },
  { en: "Mary Lee", ar: "ماري لي", ja: "メアリー・リー", fr: "Marie Lee" },
  {
    en: "James Brown",
    ar: "جيمس براون",
    ja: "ジェームズ・ブラウン",
    fr: "James Brown",
  },
  {
    en: "Emma Wilson",
    ar: "إيما ويلسون",
    ja: "エマ・ウィルソン",
    fr: "Emma Wilson",
  },
  {
    en: "Liam Taylor",
    ar: "ليام تايلور",
    ja: "リアム・テイラー",
    fr: "Liam Taylor",
  },
  {
    en: "Olivia Martinez",
    ar: "أوليفيا مارتينيز",
    ja: "オリビア・マルティネス",
    fr: "Olivia Martinez",
  },

  {
    en: "Youssef El Amrani",
    ar: "يوسف العمراني",
    ja: "ユセフ・エル・アムラニ",
    fr: "Youssef El Amrani",
  },
  {
    en: "Fatima Zahra",
    ar: "فاطمة الزهراء",
    ja: "ファティマ・ザハラ",
    fr: "Fatima Zahra",
  },
  {
    en: "Hiroshi Tanaka",
    ar: "هيروشي تاناكا",
    ja: "田中宏",
    fr: "Hiroshi Tanaka",
  },
  {
    en: "Sakura Yamamoto",
    ar: "ساكورا ياماموتو",
    ja: "山本さくら",
    fr: "Sakura Yamamoto",
  },
  {
    en: "Jean Dupont",
    ar: "جان دوبون",
    ja: "ジャン・デュポン",
    fr: "Jean Dupont",
  },
  {
    en: "Marie Dubois",
    ar: "ماري دوبوا",
    ja: "マリー・デュボワ",
    fr: "Marie Dubois",
  },
  {
    en: "Carlos Mendes",
    ar: "كارلوس مينديز",
    ja: "カルロス・メンデス",
    fr: "Carlos Mendes",
  },
  {
    en: "Ana Ferreira",
    ar: "آنا فيريرا",
    ja: "アナ・フェレイラ",
    fr: "Ana Ferreira",
  },

  { en: "Luca Rossi", ar: "لوكا روسي", ja: "ルカ・ロッシ", fr: "Luca Rossi" },
  {
    en: "Giulia Bianchi",
    ar: "جوليا بيانكي",
    ja: "ジュリア・ビアンキ",
    fr: "Giulia Bianchi",
  },
  {
    en: "Hans Müller",
    ar: "هانز مولر",
    ja: "ハンス・ミュラー",
    fr: "Hans Müller",
  },
  {
    en: "Anna Schmidt",
    ar: "آنا شميت",
    ja: "アンナ・シュミット",
    fr: "Anna Schmidt",
  },
  {
    en: "Ivan Petrov",
    ar: "إيفان بيتروف",
    ja: "イワン・ペトロフ",
    fr: "Ivan Petrov",
  },
  {
    en: "Olga Ivanova",
    ar: "أولغا إيفانوفا",
    ja: "オルガ・イワノワ",
    fr: "Olga Ivanova",
  },
  { en: "Wei Zhang", ar: "وي تشانغ", ja: "張偉", fr: "Wei Zhang" },
  { en: "Li Na", ar: "لي نا", ja: "李娜", fr: "Li Na" },

  {
    en: "Min-jun Kim",
    ar: "مين جون كيم",
    ja: "キム・ミンジュン",
    fr: "Min-jun Kim",
  },
  { en: "Seo-yeon Lee", ar: "سو يون لي", ja: "イ・ソヨン", fr: "Seo-yeon Lee" },
  {
    en: "Rajesh Kumar",
    ar: "راجेश كومار",
    ja: "ラジェシュ・クマール",
    fr: "Rajesh Kumar",
  },
  {
    en: "Priya Sharma",
    ar: "بريا شارما",
    ja: "プリヤ・シャルマ",
    fr: "Priya Sharma",
  },
  {
    en: "Ahmed Hassan",
    ar: "أحمد حسن",
    ja: "アフメド・ハッサン",
    fr: "Ahmed Hassan",
  },
  {
    en: "Amina Khalil",
    ar: "أمينة خليل",
    ja: "アミナ・ハリル",
    fr: "Amina Khalil",
  },
  {
    en: "Mehmet Yılmaz",
    ar: "محمد يلماز",
    ja: "メフメト・ユルマズ",
    fr: "Mehmet Yılmaz",
  },
  {
    en: "Ayşe Demir",
    ar: "عائشة دمير",
    ja: "アイシェ・デミル",
    fr: "Ayşe Demir",
  },

  {
    en: "João Silva",
    ar: "جواو سيلفا",
    ja: "ジョアン・シルバ",
    fr: "João Silva",
  },
  {
    en: "Beatriz Costa",
    ar: "بياتريز كوستا",
    ja: "ベアトリス・コスタ",
    fr: "Beatriz Costa",
  },
  {
    en: "Alejandro Ruiz",
    ar: "أليخاندرو رويز",
    ja: "アレハンドロ・ルイス",
    fr: "Alejandro Ruiz",
  },
  {
    en: "Lucía Fernández",
    ar: "لوسيا فرنانديز",
    ja: "ルシア・フェルナンデス",
    fr: "Lucía Fernández",
  },
  {
    en: "Mateo González",
    ar: "ماتيو غونزاليس",
    ja: "マテオ・ゴンザレス",
    fr: "Mateo González",
  },
  {
    en: "Sofía Herrera",
    ar: "صوفيا هيريرا",
    ja: "ソフィア・エレーラ",
    fr: "Sofía Herrera",
  },
  {
    en: "Andrés Castillo",
    ar: "أندريس كاستيلو",
    ja: "アンドレス・カスティージョ",
    fr: "Andrés Castillo",
  },
  {
    en: "Camila Torres",
    ar: "كاميلا توريس",
    ja: "カミラ・トーレス",
    fr: "Camila Torres",
  },

  {
    en: "Omar Benali",
    ar: "عمر بنعلي",
    ja: "オマル・ベナリ",
    fr: "Omar Benali",
  },
  {
    en: "Salma Idrissi",
    ar: "سلمى الإدريسي",
    ja: "サルマ・イドリッシ",
    fr: "Salma Idrissi",
  },
  {
    en: "Rachid Bensalem",
    ar: "رشيد بنسالم",
    ja: "ラシッド・ベンサレム",
    fr: "Rachid Bensalem",
  },
  {
    en: "Nadia El Fassi",
    ar: "نادية الفاسي",
    ja: "ナディア・エル・ファシ",
    fr: "Nadia El Fassi",
  },

  {
    en: "Kwame Mensah",
    ar: "كوامي منساه",
    ja: "クワメ・メンサー",
    fr: "Kwame Mensah",
  },
  {
    en: "Ama Nkrumah",
    ar: "أما نكروما",
    ja: "アマ・ンクルマ",
    fr: "Ama Nkrumah",
  },
  {
    en: "Thabo Dlamini",
    ar: "ثابو دلاميني",
    ja: "タボ・ドラミニ",
    fr: "Thabo Dlamini",
  },
  {
    en: "Zanele Nkosi",
    ar: "زانيل نكوسي",
    ja: "ザネレ・ンコシ",
    fr: "Zanele Nkosi",
  },

  {
    en: "Ethan Miller",
    ar: "إيثان ميلر",
    ja: "イーサン・ミラー",
    fr: "Ethan Miller",
  },
  { en: "Ava Davis", ar: "آفا ديفيس", ja: "エヴァ・デイビス", fr: "Ava Davis" },
  {
    en: "Noah Wilson",
    ar: "نوح ويلسون",
    ja: "ノア・ウィルソン",
    fr: "Noah Wilson",
  },
  {
    en: "Mason Moore",
    ar: "ماسون مور",
    ja: "メイソン・ムーア",
    fr: "Mason Moore",
  },

  { en: "Yuki Sato", ar: "يوكي ساتو", ja: "佐藤優希", fr: "Yuki Sato" },
  {
    en: "Haruto Suzuki",
    ar: "هاروتو سوزوكي",
    ja: "鈴木陽翔",
    fr: "Haruto Suzuki",
  },
  {
    en: "Aiko Takahashi",
    ar: "أيكو تاكاهاشي",
    ja: "高橋愛子",
    fr: "Aiko Takahashi",
  },
  { en: "Ren Nakamura", ar: "رين ناكامورا", ja: "中村蓮", fr: "Ren Nakamura" },

  { en: "Chen Wei", ar: "تشن وي", ja: "陳偉", fr: "Chen Wei" },
  { en: "Wang Fang", ar: "وانغ فانغ", ja: "王芳", fr: "Wang Fang" },
  { en: "Liu Yang", ar: "ليو يانغ", ja: "劉洋", fr: "Liu Yang" },
  { en: "Zhao Min", ar: "تشاو مين", ja: "趙敏", fr: "Zhao Min" },

  { en: "Ali Rezaei", ar: "علي رضائي", ja: "アリ・レザエイ", fr: "Ali Rezaei" },
  {
    en: "Sara Hosseini",
    ar: "سارا حسيني",
    ja: "サラ・ホセイニ",
    fr: "Sara Hosseini",
  },
  {
    en: "Hassan Al-Farsi",
    ar: "حسن الفارسي",
    ja: "ハッサン・アルファルシ",
    fr: "Hassan Al-Farsi",
  },
  {
    en: "Layla Al-Sabah",
    ar: "ليلى الصباح",
    ja: "ライラ・アルサバー",
    fr: "Layla Al-Sabah",
  },

  {
    en: "Dmitry Smirnov",
    ar: "ديمتري سميرنوف",
    ja: "ドミトリー・スミルノフ",
    fr: "Dmitry Smirnov",
  },
  {
    en: "Elena Popova",
    ar: "إيلينا بوبوفا",
    ja: "エレナ・ポポワ",
    fr: "Elena Popova",
  },
  {
    en: "Sergey Volkov",
    ar: "سيرغي فولكوف",
    ja: "セルゲイ・ヴォルコフ",
    fr: "Sergey Volkov",
  },
  {
    en: "Natalia Orlova",
    ar: "ناتاليا أورلوفا",
    ja: "ナタリア・オルロワ",
    fr: "Natalia Orlova",
  },

  {
    en: "Peter Novak",
    ar: "بيتر نوفاك",
    ja: "ピーター・ノヴァク",
    fr: "Peter Novak",
  },
  {
    en: "Eva Horvat",
    ar: "إيفا هورفات",
    ja: "エヴァ・ホルヴァート",
    fr: "Eva Horvat",
  },
  {
    en: "Marek Kowalski",
    ar: "ماريك كوفالسكي",
    ja: "マレク・コヴァルスキ",
    fr: "Marek Kowalski",
  },
  {
    en: "Anna Nowak",
    ar: "آنا نوفاك",
    ja: "アンナ・ノヴァク",
    fr: "Anna Nowak",
  },
];

export const COMPANIES = [
  { en: "TechCorp", ar: "تك كورب", ja: "テックコープ", fr: "TechCorp" },
  { en: "DesignHub", ar: "ديزاين هاب", ja: "デザインハブ", fr: "DesignHub" },
  { en: "DataWorks", ar: "داتا وركس", ja: "データワークス", fr: "DataWorks" },
  { en: "CloudNine", ar: "كلاود ناين", ja: "クラウドナイン", fr: "CloudNine" },
  {
    en: "NextGen Solutions",
    ar: "نيكست جن سولوشنز",
    ja: "ネクストジェンソリューションズ",
    fr: "NextGen Solutions",
  },
  { en: "AlphaTech", ar: "ألفا تك", ja: "アルファテック", fr: "AlphaTech" },
  {
    en: "Bright Minds",
    ar: "برايت مايندز",
    ja: "ブライトマインズ",
    fr: "Bright Minds",
  },
  { en: "CodeWorks", ar: "كود وركس", ja: "コードワークス", fr: "CodeWorks" },

  {
    en: "Atlas Systems",
    ar: "أطلس سيستمز",
    ja: "アトラスシステムズ",
    fr: "Atlas Systems",
  },
  { en: "Nova Labs", ar: "نوفا لابز", ja: "ノバラボ", fr: "Nova Labs" },
  {
    en: "Skyline Tech",
    ar: "سكاي لاين تك",
    ja: "スカイラインテック",
    fr: "Skyline Tech",
  },
  {
    en: "FusionSoft",
    ar: "فيوجن سوفت",
    ja: "フュージョンソフト",
    fr: "FusionSoft",
  },
  {
    en: "Vertex Solutions",
    ar: "فيرتكس سولوشنز",
    ja: "バーテックスソリューションズ",
    fr: "Vertex Solutions",
  },
  {
    en: "QuantumLeap",
    ar: "كوانتم ليب",
    ja: "クアンタムリープ",
    fr: "QuantumLeap",
  },
  { en: "BlueWave", ar: "بلو ويف", ja: "ブルーウェーブ", fr: "BlueWave" },
  {
    en: "PixelForge",
    ar: "بيكسل فورج",
    ja: "ピクセルフォージ",
    fr: "PixelForge",
  },

  { en: "GlobalNet", ar: "جلوبال نت", ja: "グローバルネット", fr: "GlobalNet" },
  { en: "SmartCore", ar: "سمارت كور", ja: "スマートコア", fr: "SmartCore" },
  { en: "InnovaTech", ar: "إنوفا تك", ja: "イノバテック", fr: "InnovaTech" },
  { en: "CyberLink", ar: "سايبر لينك", ja: "サイバーリンク", fr: "CyberLink" },
  { en: "NextWave", ar: "نكست ويف", ja: "ネクストウェーブ", fr: "NextWave" },
  {
    en: "LogicStream",
    ar: "لوجيك ستريم",
    ja: "ロジックストリーム",
    fr: "LogicStream",
  },
  { en: "CoreVision", ar: "كور فيجن", ja: "コアビジョン", fr: "CoreVision" },
  {
    en: "Apex Digital",
    ar: "أبيكس ديجيتال",
    ja: "エーペックスデジタル",
    fr: "Apex Digital",
  },

  {
    en: "Zenith Corp",
    ar: "زينيث كورب",
    ja: "ゼニスコープ",
    fr: "Zenith Corp",
  },
  { en: "OmniTech", ar: "أومني تك", ja: "オムニテック", fr: "OmniTech" },
  { en: "PrimeSoft", ar: "برايم سوفت", ja: "プライムソフト", fr: "PrimeSoft" },
  {
    en: "Orbit Systems",
    ar: "أوربيت سيستمز",
    ja: "オービットシステムズ",
    fr: "Orbit Systems",
  },
  {
    en: "Helix Solutions",
    ar: "هيليكس سولوشنز",
    ja: "ヘリックスソリューションズ",
    fr: "Helix Solutions",
  },
  {
    en: "Nexus Group",
    ar: "نيكسوس جروب",
    ja: "ネクサスグループ",
    fr: "Nexus Group",
  },
  { en: "EvoTech", ar: "إيفو تك", ja: "エボテック", fr: "EvoTech" },
  {
    en: "Matrix Labs",
    ar: "ماتريكس لابز",
    ja: "マトリックスラボ",
    fr: "Matrix Labs",
  },

  { en: "TerraSoft", ar: "تيرا سوفت", ja: "テラソフト", fr: "TerraSoft" },
  { en: "BrightCode", ar: "برايت كود", ja: "ブライトコード", fr: "BrightCode" },
  {
    en: "SilverLine",
    ar: "سيلفر لاين",
    ja: "シルバーライン",
    fr: "SilverLine",
  },
  {
    en: "GreenField Tech",
    ar: "غرين فيلد تك",
    ja: "グリーンフィールドテック",
    fr: "GreenField Tech",
  },
  { en: "RedStone", ar: "ريد ستون", ja: "レッドストーン", fr: "RedStone" },
  { en: "BlueCore", ar: "بلو كور", ja: "ブルーコア", fr: "BlueCore" },
  {
    en: "Next Horizon",
    ar: "نكست هورايزون",
    ja: "ネクストホライズン",
    fr: "Next Horizon",
  },
  {
    en: "OpenSphere",
    ar: "أوبن سفير",
    ja: "オープンスフィア",
    fr: "OpenSphere",
  },

  { en: "Sakura Tech", ar: "ساكورا تك", ja: "サクラテック", fr: "Sakura Tech" },
  {
    en: "Hikari Systems",
    ar: "هيكاري سيستمز",
    ja: "ヒカリシステムズ",
    fr: "Hikari Systems",
  },
  { en: "Shinrai Labs", ar: "شينراي لابز", ja: "信頼ラボ", fr: "Shinrai Labs" },
  {
    en: "Mirai Solutions",
    ar: "ميراي سولوشنز",
    ja: "未来ソリューションズ",
    fr: "Mirai Solutions",
  },

  {
    en: "Al Noor Tech",
    ar: "النور تك",
    ja: "アルヌールテック",
    fr: "Al Noor Tech",
  },
  {
    en: "Baraka Systems",
    ar: "بركة سيستمز",
    ja: "バラカシステムズ",
    fr: "Baraka Systems",
  },
  {
    en: "Cedars Group",
    ar: "سيدارز جروب",
    ja: "シダーズグループ",
    fr: "Cedars Group",
  },
  {
    en: "Maghreb Solutions",
    ar: "مغرب سولوشنز",
    ja: "マグレブソリューションズ",
    fr: "Maghreb Solutions",
  },

  { en: "Andes Tech", ar: "أنديز تك", ja: "アンデステック", fr: "Andes Tech" },
  {
    en: "Pampa Digital",
    ar: "بامبا ديجيتال",
    ja: "パンパデジタル",
    fr: "Pampa Digital",
  },
  {
    en: "Rio Systems",
    ar: "ريو سيستمز",
    ja: "リオシステムズ",
    fr: "Rio Systems",
  },
  {
    en: "Soluciones Nova",
    ar: "سولوسيونيس نوفا",
    ja: "ソルシオネスノバ",
    fr: "Soluciones Nova",
  },

  {
    en: "Nordic Tech",
    ar: "نورديك تك",
    ja: "ノルディックテック",
    fr: "Nordic Tech",
  },
  {
    en: "Baltic Systems",
    ar: "بالتيك سيستمز",
    ja: "バルティックシステムズ",
    fr: "Baltic Systems",
  },
  {
    en: "Alpine Labs",
    ar: "ألباين لابز",
    ja: "アルパインラボ",
    fr: "Alpine Labs",
  },
  { en: "EuroCore", ar: "يورو كور", ja: "ユーロコア", fr: "EuroCore" },

  { en: "DesertTech", ar: "ديزرت تك", ja: "デザートテック", fr: "DesertTech" },
  {
    en: "Savannah Systems",
    ar: "سافانا سيستمز",
    ja: "サバンナシステムズ",
    fr: "Savannah Systems",
  },
  {
    en: "Nile Digital",
    ar: "النيل ديجيتال",
    ja: "ナイルデジタル",
    fr: "Nile Digital",
  },
  {
    en: "Sahara Labs",
    ar: "الصحراء لابز",
    ja: "サハララボ",
    fr: "Sahara Labs",
  },

  {
    en: "Pacific Tech",
    ar: "باسيفيك تك",
    ja: "パシフィックテック",
    fr: "Pacific Tech",
  },
  {
    en: "Oceanic Systems",
    ar: "أوشيانيك سيستمز",
    ja: "オーシャニックシステムズ",
    fr: "Oceanic Systems",
  },
  {
    en: "Coral Digital",
    ar: "كورال ديجيتال",
    ja: "コーラルデジタル",
    fr: "Coral Digital",
  },
  {
    en: "IslandSoft",
    ar: "آيلاند سوفت",
    ja: "アイランドソフト",
    fr: "IslandSoft",
  },
];

export const DEGREES = [
  {
    en: "Bachelor of Science",
    ar: "بكالوريوس علوم",
    ja: "理学士",
    fr: "Licence en sciences",
  },
  {
    en: "Master of Engineering",
    ar: "ماجستير هندسة",
    ja: "工学修士",
    fr: "Master en ingénierie",
  },
  {
    en: "Bachelor of Arts",
    ar: "بكالوريوس آداب",
    ja: "文学士",
    fr: "Licence en arts",
  },
  {
    en: "Master of Science",
    ar: "ماجستير علوم",
    ja: "理学修士",
    fr: "Master en sciences",
  },
  { en: "MBA", ar: "ماجستير إدارة أعمال", ja: "経営学修士", fr: "MBA" },

  {
    en: "Bachelor of Engineering",
    ar: "بكالوريوس هندسة",
    ja: "工学士",
    fr: "Licence en ingénierie",
  },
  {
    en: "Master of Arts",
    ar: "ماجستير آداب",
    ja: "文学修士",
    fr: "Master en arts",
  },
  {
    en: "Doctor of Philosophy",
    ar: "دكتوراه في الفلسفة",
    ja: "博士（哲学）",
    fr: "Doctorat",
  },
  {
    en: "Bachelor of Business Administration",
    ar: "بكالوريوس إدارة أعمال",
    ja: "経営学士",
    fr: "Licence en gestion",
  },
  {
    en: "Master of Finance",
    ar: "ماجستير مالية",
    ja: "金融学修士",
    fr: "Master en finance",
  },

  {
    en: "Bachelor of Information Technology",
    ar: "بكالوريوس تكنولوجيا المعلومات",
    ja: "情報技術学士",
    fr: "Licence en informatique",
  },
  {
    en: "Master of Computer Science",
    ar: "ماجستير علوم الحاسوب",
    ja: "情報工学修士",
    fr: "Master en informatique",
  },
  {
    en: "Bachelor of Law",
    ar: "بكالوريوس قانون",
    ja: "法学士",
    fr: "Licence en droit",
  },
  {
    en: "Master of Law",
    ar: "ماجستير قانون",
    ja: "法学修士",
    fr: "Master en droit",
  },
  {
    en: "Doctor of Medicine",
    ar: "دكتوراه في الطب",
    ja: "医学博士",
    fr: "Doctorat en médecine",
  },

  {
    en: "Bachelor of Architecture",
    ar: "بكالوريوس عمارة",
    ja: "建築学士",
    fr: "Licence en architecture",
  },
  {
    en: "Master of Architecture",
    ar: "ماجستير عمارة",
    ja: "建築学修士",
    fr: "Master en architecture",
  },
  {
    en: "Bachelor of Education",
    ar: "بكالوريوس تربية",
    ja: "教育学士",
    fr: "Licence en éducation",
  },
  {
    en: "Master of Education",
    ar: "ماجستير تربية",
    ja: "教育学修士",
    fr: "Master en éducation",
  },
  {
    en: "Bachelor of Economics",
    ar: "بكالوريوس اقتصاد",
    ja: "経済学士",
    fr: "Licence en économie",
  },

  {
    en: "Master of Economics",
    ar: "ماجستير اقتصاد",
    ja: "経済学修士",
    fr: "Master en économie",
  },
  {
    en: "Bachelor of Nursing",
    ar: "بكالوريوس تمريض",
    ja: "看護学士",
    fr: "Licence en soins infirmiers",
  },
  {
    en: "Master of Public Health",
    ar: "ماجستير الصحة العامة",
    ja: "公衆衛生学修士",
    fr: "Master en santé publique",
  },
  {
    en: "Bachelor of Psychology",
    ar: "بكالوريوس علم النفس",
    ja: "心理学士",
    fr: "Licence en psychologie",
  },
  {
    en: "Master of Psychology",
    ar: "ماجستير علم النفس",
    ja: "心理学修士",
    fr: "Master en psychologie",
  },
];

export const TASKS = [
  {
    en: "Implemented user authentication system using JWT and OAuth2 protocols",
    ar: "تنفيذ نظام مصادقة المستخدم باستخدام بروتوكولات JWT و OAuth2",
    ja: "JWTとOAuth2プロトコルを使用したユーザー認証システムの実装",
    fr: "Implémentation du système d'authentification des utilisateurs à l'aide des protocoles JWT et OAuth2",
  },
  {
    en: "Refactored legacy codebase to improve maintainability and reduce technical debt by 35%",
    ar: "إعادة هيكلة قاعدة الكود القديمة لتحسين الصيانة وتقليل الديون التقنية بنسبة 35٪",
    ja: "レガシーコードベースのリファクタリングにより保守性を向上させ、技術的負債を35%削減",
    fr: "Refonte du code legacy pour améliorer la maintenabilité et réduire la dette technique de 35 %",
  },
  {
    en: "Developed real-time notification system with WebSockets for instant user updates",
    ar: "تطوير نظام إشعارات في الوقت الفعلي باستخدام WebSockets لتحديثات فورية للمستخدمين",
    ja: "WebSocketsを使用したリアルタイム通知システムの開発（ユーザーへの即時更新）",
    fr: "Développement d'un système de notifications en temps réel avec WebSockets pour des mises à jour instantanées des utilisateurs",
  },
  {
    en: "Integrated CI/CD pipeline using GitHub Actions for automated testing and deployment",
    ar: "دمج خط أنابيب CI/CD باستخدام GitHub Actions للاختبار والنشر الآلي",
    ja: "GitHub Actionsを使用したCI/CDパイプラインの統合（自動テストとデプロイ）",
    fr: "Intégration d'un pipeline CI/CD avec GitHub Actions pour les tests et déploiements automatisés",
  },
  {
    en: "Optimized SQL database queries resulting in 45% faster response times under load",
    ar: "تحسين استعلامات قاعدة بيانات SQL مما أدى إلى تسريع الاستجابة بنسبة 45٪ تحت الحمل",
    ja: "SQLデータベースクエリの最適化により、負荷時応答時間を45%短縮",
    fr: "Optimisation des requêtes SQL de la base de données entraînant une réduction de 45 % des temps de réponse en charge",
  },
  {
    en: "Designed interactive data visualization dashboards using Chart.js and D3.js",
    ar: "تصميم لوحات تحكم تفاعلية لتصور البيانات باستخدام Chart.js و D3.js",
    ja: "Chart.jsとD3.jsを使用したインタラクティブなデータ可視化ダッシュボードの設計",
    fr: "Conception de tableaux de bord de visualisation de données interactifs avec Chart.js et D3.js",
  },
  {
    en: "Resolved critical security vulnerabilities identified during penetration testing",
    ar: "حل الثغرات الأمنية الحرجة التي تم تحديدها أثناء اختبار الاختراق",
    ja: "侵入テストで特定された重大なセキュリティ脆弱性の解決",
    fr: "Résolution des vulnérabilités de sécurité critiques identifiées lors des tests d'intrusion",
  },
  {
    en: "Collaborated with UX team to redesign mobile application interface for improved usability",
    ar: "التعاون مع فريق تجربة المستخدم لإعادة تصميم واجهة تطبيق الهاتف المحمول لتحسين سهولة الاستخدام",
    ja: "UXチームと協力したモバイルアプリインターフェースの再設計（ユーザビリティ向上）",
    fr: "Collaboration avec l'équipe UX pour redesigner l'interface de l'application mobile afin d'améliorer l'utilisabilité",
  },
  {
    en: "Developed RESTful APIs for seamless integration with third-party payment gateways",
    ar: "تطوير واجهات برمجة تطبيقات RESTful للتكامل السلس مع بوابات الدفع الخارجية",
    ja: "サードパーティ決済ゲートウェイとのシームレス統合のためのRESTful API開発",
    fr: "Développement d'API RESTful pour une intégration fluide avec les passerelles de paiement tierces",
  },
  {
    en: "Wrote unit and integration tests achieving 92% code coverage across core modules",
    ar: "كتابة اختبارات الوحدات والتكامل لتحقيق تغطية كود بنسبة 92٪ عبر الوحدات الأساسية",
    ja: "コアモジュール全体で92%のコードカバレッジを達成するユニットテストと統合テストの作成",
    fr: "Rédaction de tests unitaires et d'intégration atteignant 92 % de couverture de code sur les modules principaux",
  },
  {
    en: "Migrated legacy monolithic application to microservices architecture using Docker",
    ar: "ترحيل التطبيق الأحادي القديم إلى هندسة الخدمات المصغرة باستخدام Docker",
    ja: "Dockerを使用したレガシーモノリシックアプリケーションのマイクロサービスアーキテクチャへの移行",
    fr: "Migration d'une application monolithique legacy vers une architecture microservices avec Docker",
  },
  {
    en: "Implemented accessibility standards (WCAG 2.1) across the entire web platform",
    ar: "تنفيذ معايير الوصولية (WCAG 2.1) عبر المنصة الويب بأكملها",
    ja: "ウェブプラットフォーム全体へのアクセシビリティ基準（WCAG 2.1）の実装",
    fr: "Implémentation des normes d'accessibilité (WCAG 2.1) sur l'ensemble de la plateforme web",
  },
  {
    en: "Conducted performance audit and reduced initial page load time by 60%",
    ar: "إجراء تدقيق أداء وتقليل وقت تحميل الصفحة الأولي بنسبة 60٪",
    ja: "パフォーマンス監査を実施し、初回ページロード時間を60%短縮",
    fr: "Audit de performance effectué et réduction du temps de chargement initial de la page de 60 %",
  },
  {
    en: "Integrated analytics tracking with Google Analytics 4 and custom event logging",
    ar: "دمج تتبع التحليلات مع Google Analytics 4 وسجل الأحداث المخصص",
    ja: "Google Analytics 4とカスタムイベントログを使用したアナリティクス追跡の統合",
    fr: "Intégration du suivi analytique avec Google Analytics 4 et journalisation d'événements personnalisés",
  },
  {
    en: "Led cross-functional team in delivering new feature within two-week sprint",
    ar: "قيادة فريق متعدد الوظائف لتسليم ميزة جديدة خلال سباق مدتها أسبوعان",
    ja: "2週間のスプリント内で新機能を提供するクロスファンクショナルチームのリード",
    fr: "Direction d'une équipe pluridisciplinaire pour la livraison d'une nouvelle fonctionnalité dans un sprint de deux semaines",
  },
  {
    en: "Automated email campaign system using SendGrid API and template engine",
    ar: "أتمتة نظام حملات البريد الإلكتروني باستخدام SendGrid API ومحرك القوالب",
    ja: "SendGrid APIとテンプレートエンジンを使用したメールキャンペーンシステムの自動化",
    fr: "Automatisation du système de campagnes email avec l'API SendGrid et un moteur de templates",
  },
  {
    en: "Fixed 28 high-priority bugs reported in production environment",
    ar: "إصلاح 28 خطأ ذا أولوية عالية تم الإبلاغ عنه في بيئة الإنتاج",
    ja: "本番環境で報告された28件の高優先度バグの修正",
    fr: "Correction de 28 bugs de haute priorité signalés en environnement de production",
  },
  {
    en: "Created comprehensive API documentation using Swagger and Postman collections",
    ar: "إنشاء وثائق API شاملة باستخدام Swagger ومجموعات Postman",
    ja: "SwaggerとPostmanコレクションを使用した包括的なAPIドキュメントの作成",
    fr: "Création d'une documentation API complète avec Swagger et collections Postman",
  },
  {
    en: "Implemented caching layer with Redis to handle high-traffic scenarios",
    ar: "تنفيذ طبقة تخزين مؤقت باستخدام Redis للتعامل مع سيناريوهات الحركة العالية",
    ja: "Redisを使用したキャッシュレイヤーの実装（高トラフィック対応）",
    fr: "Implémentation d'une couche de cache avec Redis pour gérer les scénarios de trafic élevé",
  },
  {
    en: "Developed multilingual support for Arabic, English, and French interfaces",
    ar: "تطوير دعم متعدد اللغات لواجهات العربية والإنجليزية والفرنسية",
    ja: "アラビア語・英語・フランス語対応の多言語サポートの開発",
    fr: "Développement du support multilingue pour les interfaces en arabe, anglais et français",
  },
  {
    en: "Conducted user acceptance testing with 150 beta testers and incorporated feedback",
    ar: "إجراء اختبار قبول المستخدم مع 150 مختبر تجريبي ودمج الملاحظات",
    ja: "150名のベータテスターによるユーザー受入テストの実施とフィードバックの反映",
    fr: "Tests d'acceptation utilisateur avec 150 testeurs bêta et intégration des retours",
  },
  {
    en: "Optimized frontend bundle size reducing it from 4.2 MB to 1.8 MB",
    ar: "تحسين حجم حزمة الواجهة الأمامية من 4.2 ميغابايت إلى 1.8 ميغابايت",
    ja: "フロントエンドバンドルサイズの最適化（4.2MBから1.8MBへ削減）",
    fr: "Optimisation de la taille du bundle frontend, réduite de 4,2 Mo à 1,8 Mo",
  },
  {
    en: "Integrated machine learning model for personalized content recommendations",
    ar: "دمج نموذج تعلم آلي للتوصيات بالمحتوى الشخصي",
    ja: "パーソナライズドコンテンツ推薦のための機械学習モデルの統合",
    fr: "Intégration d'un modèle d'apprentissage automatique pour les recommandations de contenu personnalisées",
  },
  {
    en: "Updated all dependencies to latest stable versions and resolved compatibility issues",
    ar: "تحديث جميع التبعيات إلى أحدث الإصدارات المستقرة وحل مشكلات التوافق",
    ja: "すべての依存関係を最新の安定版に更新し、互換性問題を解決",
    fr: "Mise à jour de toutes les dépendances vers les versions stables les plus récentes et résolution des problèmes de compatibilité",
  },
  {
    en: "Built admin dashboard with role-based access control and audit logging",
    ar: "بناء لوحة تحكم إدارية مع التحكم في الوصول القائم على الأدوار وسجل التدقيق",
    ja: "ロールベースアクセス制御と監査ログ付き管理者ダッシュボードの構築",
    fr: "Construction d'un tableau de bord admin avec contrôle d'accès basé sur les rôles et journalisation d'audit",
  },
  {
    en: "Implemented dark mode toggle with system preference detection",
    ar: "تنفيذ تبديل الوضع الداكن مع اكتشاف تفضيلات النظام",
    ja: "システム設定検知付きダークモード切り替えの実装",
    fr: "Implémentation du basculement en mode sombre avec détection des préférences système",
  },
  {
    en: "Streamlined deployment process reducing average release time from 4 hours to 45 minutes",
    ar: "تبسيط عملية النشر مما قلل متوسط وقت الإصدار من 4 ساعات إلى 45 دقيقة",
    ja: "デプロイプロセスを効率化し、平均リリース時間を4時間から45分に短縮",
    fr: "Optimisation du processus de déploiement réduisant le temps moyen de mise en production de 4 heures à 45 minutes",
  },
  {
    en: "Developed file upload service with virus scanning and size validation",
    ar: "تطوير خدمة تحميل الملفات مع فحص الفيروسات والتحقق من الحجم",
    ja: "ウイルススキャンとサイズ検証付きファイルアップロードサービスの開発",
    fr: "Développement d'un service de téléchargement de fichiers avec analyse antivirus et validation de taille",
  },
  {
    en: "Created automated backup system for database with daily incremental snapshots",
    ar: "إنشاء نظام نسخ احتياطي آلي لقاعدة البيانات مع لقطات يومية تزايدية",
    ja: "日次増分スナップショット付きデータベース自動バックアップシステムの作成",
    fr: "Création d'un système de sauvegarde automatique de la base de données avec snapshots incrémentiels quotidiens",
  },
  {
    en: "Integrated Stripe payment processing with subscription management features",
    ar: "دمج معالجة الدفع Stripe مع ميزات إدارة الاشتراكات",
    ja: "Stripe決済処理とサブスクリプション管理機能の統合",
    fr: "Intégration du traitement des paiements Stripe avec les fonctionnalités de gestion des abonnements",
  },
  {
    en: "Conducted A/B testing on checkout flow resulting in 22% increase in conversion rate",
    ar: "إجراء اختبار A/B على تدفق الدفع مما أدى إلى زيادة معدل التحويل بنسبة 22٪",
    ja: "チェックアウトフローのA/Bテスト実施によりコンバージョン率22%向上",
    fr: "Tests A/B sur le flux de paiement entraînant une augmentation de 22 % du taux de conversion",
  },
  {
    en: "Implemented rate limiting and throttling to prevent API abuse",
    ar: "تنفيذ تقييد المعدل والخنق لمنع إساءة استخدام واجهات برمجة التطبيقات",
    ja: "API乱用防止のためのレート制限とスロットリングの実装",
    fr: "Implémentation de la limitation de débit et du throttling pour prévenir les abus d'API",
  },
  {
    en: "Developed custom reporting engine with export to PDF, Excel, and CSV formats",
    ar: "تطوير محرك تقارير مخصص مع تصدير إلى تنسيقات PDF و Excel و CSV",
    ja: "PDF・Excel・CSVエクスポート対応のカスタムレポートエンジンの開発",
    fr: "Développement d'un moteur de rapports personnalisé avec export vers PDF, Excel et CSV",
  },
  {
    en: "Upgraded server infrastructure from Heroku to AWS EC2 with auto-scaling",
    ar: "ترقية البنية التحتية للخادم من Heroku إلى AWS EC2 مع التوسع التلقائي",
    ja: "HerokuからAWS EC2へのサーバーインフラアップグレード（オートスケーリング付き）",
    fr: "Mise à niveau de l'infrastructure serveur de Heroku vers AWS EC2 avec auto-scaling",
  },
  {
    en: "Created onboarding tutorial flow with interactive step-by-step guidance",
    ar: "إنشاء تدفق دليل الإعداد مع إرشادات تفاعلية خطوة بخطوة",
    ja: "インタラクティブなステップバイステップガイド付きオンボーディングチュートリアルフローの作成",
    fr: "Création d'un flux de tutoriel d'onboarding avec guidage interactif étape par étape",
  },
  {
    en: "Optimized mobile app for offline functionality using service workers",
    ar: "تحسين تطبيق الهاتف المحمول لوظائف عدم الاتصال باستخدام service workers",
    ja: "サービスワーカーを使用したオフライン機能向けモバイルアプリの最適化",
    fr: "Optimisation de l'application mobile pour le fonctionnement hors ligne avec des service workers",
  },
  {
    en: "Implemented search functionality with Elasticsearch for full-text indexing",
    ar: "تنفيذ وظيفة البحث باستخدام Elasticsearch لفهرسة النص الكامل",
    ja: "全文インデックス用Elasticsearch検索機能の実装",
    fr: "Implémentation de la fonctionnalité de recherche avec Elasticsearch pour l'indexation en texte intégral",
  },
  {
    en: "Conducted security code review and applied OWASP best practices",
    ar: "إجراء مراجعة أمنية للكود وتطبيق أفضل ممارسات OWASP",
    ja: "セキュリティコードレビュー実施とOWASPベストプラクティスの適用",
    fr: "Revue de code de sécurité et application des meilleures pratiques OWASP",
  },
  {
    en: "Developed push notification service for iOS and Android using Firebase",
    ar: "تطوير خدمة الإشعارات الفورية لـ iOS و Android باستخدام Firebase",
    ja: "Firebaseを使用したiOS/Androidプッシュ通知サービスの開発",
    fr: "Développement d'un service de notifications push pour iOS et Android avec Firebase",
  },
  {
    en: "Created data export scheduler for monthly compliance reporting",
    ar: "إنشاء مجدول تصدير البيانات لتقارير الامتثال الشهرية",
    ja: "月次コンプライアンスレポート用のデータエクスポートスケジューラーの作成",
    fr: "Création d'un planificateur d'export de données pour les rapports de conformité mensuels",
  },
  {
    en: "Refined error handling and logging across all backend services",
    ar: "تحسين معالجة الأخطاء والتسجيل عبر جميع خدمات الخلفية",
    ja: "全バックエンドサービスにおけるエラーハンドリングとログ記録の洗練",
    fr: "Affinage de la gestion des erreurs et de la journalisation sur tous les services backend",
  },
  {
    en: "Implemented two-factor authentication using authenticator apps and SMS",
    ar: "تنفيذ المصادقة الثنائية باستخدام تطبيقات المصادقة والرسائل القصيرة",
    ja: "認証アプリとSMSを使用した二要素認証の実装",
    fr: "Implémentation de l'authentification à deux facteurs avec applications d'authentification et SMS",
  },
  {
    en: "Optimized image delivery with CDN and WebP format conversion",
    ar: "تحسين تسليم الصور باستخدام CDN وتحويل تنسيق WebP",
    ja: "CDNとWebP形式変換による画像配信の最適化",
    fr: "Optimisation de la livraison d'images avec CDN et conversion au format WebP",
  },
  {
    en: "Developed invoice generation module with PDF rendering and email delivery",
    ar: "تطوير وحدة إنشاء الفواتير مع عرض PDF وتسليم البريد الإلكتروني",
    ja: "PDFレンダリングとメール配信付き請求書生成モジュールの開発",
    fr: "Développement d'un module de génération de factures avec rendu PDF et envoi par email",
  },
  {
    en: "Integrated calendar synchronization with Google Calendar and Outlook",
    ar: "دمج مزامنة التقويم مع Google Calendar و Outlook",
    ja: "Google CalendarとOutlookとのカレンダー同期の統合",
    fr: "Intégration de la synchronisation du calendrier avec Google Calendar et Outlook",
  },
  {
    en: "Conducted load testing and scaled infrastructure to support 10,000 concurrent users",
    ar: "إجراء اختبار التحميل وتوسيع البنية التحتية لدعم 10000 مستخدم متزامن",
    ja: "負荷テスト実施と10,000同時ユーザー対応インフラのスケーリング",
    fr: "Tests de charge effectués et mise à l'échelle de l'infrastructure pour supporter 10 000 utilisateurs simultanés",
  },
  {
    en: "Created user feedback collection system with in-app surveys and analytics",
    ar: "إنشاء نظام جمع ملاحظات المستخدمين مع استطلاعات داخل التطبيق والتحليلات",
    ja: "アプリ内アンケートとアナリティクス付きユーザー反馈収集システムの作成",
    fr: "Création d'un système de collecte de retours utilisateurs avec sondages in-app et analyses",
  },
  {
    en: "Implemented lazy loading and code splitting for improved frontend performance",
    ar: "تنفيذ التحميل الكسول وتقسيم الكود لتحسين أداء الواجهة الأمامية",
    ja: "フロントエンドパフォーマンス向上のための遅延読み込みとコード分割の実装",
    fr: "Implémentation du lazy loading et du code splitting pour améliorer les performances frontend",
  },
  {
    en: "Developed webhook system for real-time data synchronization with external platforms",
    ar: "تطوير نظام webhook لمزامنة البيانات في الوقت الفعلي مع المنصات الخارجية",
    ja: "外部プラットフォームとのリアルタイムデータ同期用Webhookシステムの開発",
    fr: "Développement d'un système de webhooks pour la synchronisation de données en temps réel avec des plateformes externes",
  },
  {
    en: "Updated branding and UI components to align with new company design system",
    ar: "تحديث العلامة التجارية ومكونات الواجهة لتتوافق مع نظام التصميم الجديد للشركة",
    ja: "新会社デザインファミリーに合わせたブランディングとUIコンポーネントの更新",
    fr: "Mise à jour de l'identité visuelle et des composants UI pour s'aligner sur le nouveau système de design de l'entreprise",
  },
  {
    en: "Automated regression testing suite reducing manual QA effort by 70%",
    ar: "أتمتة مجموعة اختبارات الانحدار مما قلل جهد ضمان الجودة اليدوي بنسبة 70٪",
    ja: "回帰テストスイートの自動化により手動QA作業を70%削減",
    fr: "Automatisation de la suite de tests de régression réduisant l'effort manuel QA de 70 %",
  },
  {
    en: "Implemented session management with secure token refresh mechanisms",
    ar: "تنفيذ إدارة الجلسات مع آليات تحديث الرموز الآمنة",
    ja: "セキュアトークン更新メカニズム付きセッション管理の実装",
    fr: "Implémentation de la gestion des sessions avec mécanismes de rafraîchissement sécurisé des tokens",
  },
  {
    en: "Developed bulk import/export feature for user management module",
    ar: "تطوير ميزة الاستيراد/التصدير بالجملة لوحدة إدارة المستخدمين",
    ja: "ユーザー管理モジュール向け一括インポート/エクスポート機能の開発",
    fr: "Développement de la fonctionnalité d'import/export en masse pour le module de gestion des utilisateurs",
  },
  {
    en: "Integrated SMS gateway for two-factor authentication and transactional alerts",
    ar: "دمج بوابة الرسائل القصيرة للمصادقة الثنائية والتنبيهات التعاملية",
    ja: "二要素認証と取引アラート用のSMSゲートウェイ統合",
    fr: "Intégration d'une passerelle SMS pour l'authentification à deux facteurs et les alertes transactionnelles",
  },
  {
    en: "Optimized memory usage in backend services reducing server costs by 28%",
    ar: "تحسين استخدام الذاكرة في خدمات الخلفية مما خفض تكاليف الخادم بنسبة 28٪",
    ja: "バックエンドサービスのメモリ使用量最適化によりサーバーコスト28%削減",
    fr: "Optimisation de l'utilisation de la mémoire dans les services backend réduisant les coûts serveur de 28 %",
  },
  {
    en: "Created interactive map component using Leaflet.js for location-based services",
    ar: "إنشاء مكون خريطة تفاعلي باستخدام Leaflet.js للخدمات القائمة على الموقع",
    ja: "位置情報サービス向けLeaflet.jsインタラクティブマップコンポーネントの作成",
    fr: "Création d'un composant de carte interactive avec Leaflet.js pour les services basés sur la localisation",
  },
  {
    en: "Implemented audit trail for all user actions to support compliance requirements",
    ar: "تنفيذ سجل تدقيق لجميع إجراءات المستخدم لدعم متطلبات الامتثال",
    ja: "コンプライアンス要件対応の全ユーザーアクション監査証跡の実装",
    fr: "Implémentation d'une piste d'audit pour toutes les actions utilisateur afin de répondre aux exigences de conformité",
  },
  {
    en: "Developed video streaming integration with HLS protocol for on-demand content",
    ar: "تطوير تكامل بث الفيديو ببروتوكول HLS للمحتوى عند الطلب",
    ja: "オンデマンドコンテンツ向けHLSプロトコル動画ストリーミング統合の開発",
    fr: "Développement de l'intégration du streaming vidéo avec le protocole HLS pour le contenu à la demande",
  },
  {
    en: "Conducted accessibility audit and resolved 95% of identified issues",
    ar: "إجراء تدقيق وصولية وحل 95٪ من المشكلات المحددة",
    ja: "アクセシビリティ監査実施と特定問題の95%解決",
    fr: "Audit d'accessibilité effectué et résolution de 95 % des problèmes identifiés",
  },
  {
    en: "Integrated third-party messaging service for in-app chat functionality",
    ar: "دمج خدمة رسائل خارجية لوظيفة الدردشة داخل التطبيق",
    ja: "アプリ内チャット機能のためのサードパーティメッセージングサービス統合",
    fr: "Intégration d'un service de messagerie tierce pour la fonctionnalité de chat in-app",
  },
  {
    en: "Created customizable dashboard widgets with drag-and-drop functionality",
    ar: "إنشاء ويدجت لوحة تحكم قابلة للتخصيص بوظيفة السحب والإفلات",
    ja: "ドラッグ＆ドロップ機能付きカスタマイズ可能ダッシュボードウィジェットの作成",
    fr: "Création de widgets de tableau de bord personnalisables avec fonctionnalité drag-and-drop",
  },
  {
    en: "Implemented data encryption at rest and in transit using AES-256",
    ar: "تنفيذ تشفير البيانات أثناء الراحة وأثناء النقل باستخدام AES-256",
    ja: "AES-256を使用した保存時および転送時のデータ暗号化の実装",
    fr: "Implémentation du chiffrement des données au repos et en transit avec AES-256",
  },
  {
    en: "Developed task management module with Kanban board and Gantt chart views",
    ar: "تطوير وحدة إدارة المهام مع لوحات كانبان ومخططات جانت",
    ja: "Kanbanボードとガントチャートビュー付きタスク管理モジュールの開発",
    fr: "Développement d'un module de gestion des tâches avec vues Kanban et diagramme de Gantt",
  },
  {
    en: "Optimized search algorithm to return results in under 200ms average",
    ar: "تحسين خوارزمية البحث لإرجاع النتائج في أقل من 200 مللي ثانية في المتوسط",
    ja: "平均200ms未満で結果を返す検索アルゴリズムの最適化",
    fr: "Optimisation de l'algorithme de recherche pour renvoyer les résultats en moins de 200 ms en moyenne",
  },
  {
    en: "Integrated CRM system with Salesforce for lead tracking and synchronization",
    ar: "دمج نظام CRM مع Salesforce لتتبع العملاء المحتملين والمزامنة",
    ja: "リード追跡と同期のためのSalesforce CRMシステム統合",
    fr: "Intégration du système CRM avec Salesforce pour le suivi des leads et la synchronisation",
  },
  {
    en: "Created automated invoice reconciliation tool reducing manual processing time by 80%",
    ar: "إنشاء أداة تسوية فواتير آلية قللت وقت المعالجة اليدوي بنسبة 80٪",
    ja: "手動処理時間を80%削減する自動請求書照合ツールの作成",
    fr: "Création d'un outil de rapprochement automatique des factures réduisant le temps de traitement manuel de 80 %",
  },
  {
    en: "Implemented real-time collaboration features using Socket.io",
    ar: "تنفيذ ميزات التعاون في الوقت الفعلي باستخدام Socket.io",
    ja: "Socket.ioを使用したリアルタイムコラボレーション機能の実装",
    fr: "Implémentation de fonctionnalités de collaboration en temps réel avec Socket.io",
  },
  {
    en: "Upgraded frontend framework from Angular 12 to Angular 18",
    ar: "ترقية إطار عمل الواجهة الأمامية من Angular 12 إلى Angular 18",
    ja: "Angular 12からAngular 18へのフロントエンドフレームワークアップグレード",
    fr: "Mise à niveau du framework frontend d'Angular 12 à Angular 18",
  },
  {
    en: "Developed AI-powered search suggestions using natural language processing",
    ar: "تطوير اقتراحات بحث مدعومة بالذكاء الاصطناعي باستخدام معالجة اللغة الطبيعية",
    ja: "自然言語処理を使用したAI駆動型検索提案の開発",
    fr: "Développement de suggestions de recherche basées sur l'IA avec traitement du langage naturel",
  },
  {
    en: "Created role-based permission system with granular access controls",
    ar: "إنشاء نظام صلاحيات قائم على الأدوار مع ضوابط وصول دقيقة",
    ja: "きめ細かいアクセス制御付きロールベース権限システムの作成",
    fr: "Création d'un système de permissions basé sur les rôles avec contrôles d'accès granulaires",
  },
  {
    en: "Integrated weather API for location-specific service availability display",
    ar: "دمج واجهة برمجة تطبيقات الطقس لعرض توافر الخدمات حسب الموقع",
    ja: "場所別サービス可用性表示のための天気API統合",
    fr: "Intégration d'une API météo pour l'affichage de la disponibilité des services selon la localisation",
  },
  {
    en: "Optimized database indexing strategy improving query performance by 55%",
    ar: "تحسين استراتيجية فهرسة قاعدة البيانات مما حسّن أداء الاستعلامات بنسبة 55٪",
    ja: "クエリパフォーマンス55%向上のデータベースインデックス戦略最適化",
    fr: "Optimisation de la stratégie d'indexation de la base de données améliorant les performances des requêtes de 55 %",
  },
  {
    en: "Developed mobile-responsive email templates with MJML framework",
    ar: "تطوير قوالب بريد إلكتروني متجاوبة مع الأجهزة المحمولة بإطار MJML",
    ja: "MJMLフレームワークを使用したモバイルレスポンシブメールテンプレートの開発",
    fr: "Développement de templates email adaptatifs mobiles avec le framework MJML",
  },
  {
    en: "Implemented background job queue with BullMQ for asynchronous processing",
    ar: "تنفيذ قائمة انتظار المهام الخلفية باستخدام BullMQ للمعالجة غير المتزامنة",
    ja: "非同期処理用BullMQバックグラウンドジョブキューの実装",
    fr: "Implémentation d'une file d'attente de tâches en arrière-plan avec BullMQ pour le traitement asynchrone",
  },
  {
    en: "Conducted usability testing and improved user satisfaction score by 18 points",
    ar: "إجراء اختبار سهولة الاستخدام وتحسين درجة رضا المستخدمين بـ18 نقطة",
    ja: "ユーザビリティテスト実施とユーザー満足度スコア18ポイント向上",
    fr: "Tests d'utilisabilité effectués et amélioration du score de satisfaction utilisateur de 18 points",
  },
  {
    en: "Integrated social login options (Google, Apple, Facebook)",
    ar: "دمج خيارات تسجيل الدخول الاجتماعي (Google و Apple و Facebook)",
    ja: "Google・Apple・Facebookのソーシャルログインオプション統合",
    fr: "Intégration des options de connexion sociale (Google, Apple, Facebook)",
  },
  {
    en: "Created analytics dashboard with real-time metrics and historical trends",
    ar: "إنشاء لوحة تحكم تحليلات مع مقاييس في الوقت الفعلي والاتجاهات التاريخية",
    ja: "リアルタイムメトリクスと履歴トレンド付きアナリティクスダッシュボードの作成",
    fr: "Création d'un tableau de bord analytique avec métriques en temps réel et tendances historiques",
  },
  {
    en: "Implemented content delivery network for static assets across global regions",
    ar: "تنفيذ شبكة تسليم محتوى للأصول الثابتة عبر المناطق العالمية",
    ja: "グローバル地域向け静的アセット用コンテンツデリバリーネットワークの実装",
    fr: "Implémentation d'un réseau de distribution de contenu pour les actifs statiques sur les régions mondiales",
  },
  {
    en: "Developed inventory management system with real-time stock level updates",
    ar: "تطوير نظام إدارة المخزون مع تحديثات مستويات المخزون في الوقت الفعلي",
    ja: "リアルタイム在庫レベル更新付き在庫管理システムの開発",
    fr: "Développement d'un système de gestion des stocks avec mises à jour en temps réel des niveaux de stock",
  },
  {
    en: "Optimized API response compression using Gzip and Brotli algorithms",
    ar: "تحسين ضغط استجابة واجهات برمجة التطبيقات باستخدام خوارزميات Gzip و Brotli",
    ja: "GzipとBrotliアルゴリズムを使用したAPI応答圧縮の最適化",
    fr: "Optimisation de la compression des réponses API avec les algorithmes Gzip et Brotli",
  },
  {
    en: "Implemented feature flag system for controlled rollout of new functionalities",
    ar: "تنفيذ نظام علم الميزات للنشر المتحكم به للوظائف الجديدة",
    ja: "新機能の制御されたロールアウト用機能フラグシステムの実装",
    fr: "Implémentation d'un système de feature flags pour le déploiement contrôlé des nouvelles fonctionnalités",
  },
  {
    en: "Created customer support ticket system with automated routing and SLA tracking",
    ar: "إنشاء نظام تذاكر دعم العملاء مع توجيه آلي وتتبع اتفاقية مستوى الخدمة",
    ja: "自動ルーティングとSLA追跡付きカスタマーサポートチケットシステムの作成",
    fr: "Création d'un système de tickets de support client avec routage automatique et suivi des SLA",
  },
  {
    en: "Integrated biometric login support for fingerprint and face recognition",
    ar: "دمج دعم تسجيل الدخول البيومتري للبصمة والتعرف على الوجه",
    ja: "指紋・顔認識対応生体認証ログインサポートの統合",
    fr: "Intégration du support de connexion biométrique pour l'empreinte digitale et la reconnaissance faciale",
  },
  {
    en: "Developed subscription billing engine with proration and upgrade handling",
    ar: "تطوير محرك فوترة الاشتراكات مع التناسب ومعالجة الترقية",
    ja: "按分とアップグレード処理付きサブスクリプションビリングエンジンの開発",
    fr: "Développement d'un moteur de facturation des abonnements avec prorata et gestion des mises à niveau",
  },
  {
    en: "Optimized frontend rendering using React Server Components",
    ar: "تحسين عرض الواجهة الأمامية باستخدام React Server Components",
    ja: "React Server Componentsを使用したフロントエンドレンダリングの最適化",
    fr: "Optimisation du rendu frontend avec React Server Components",
  },
  {
    en: "Implemented data retention policy enforcement across all storage systems",
    ar: "تنفيذ تطبيق سياسة الاحتفاظ بالبيانات عبر جميع أنظمة التخزين",
    ja: "全ストレージシステムにおけるデータ保持ポリシー実施の実装",
    fr: "Implémentation de l'application de la politique de conservation des données sur tous les systèmes de stockage",
  },
  {
    en: "Created interactive product configurator with 3D preview capabilities",
    ar: "إنشاء مُكَوِّن منتج تفاعلي مع إمكانيات معاينة ثلاثية الأبعاد",
    ja: "3Dプレビュー機能付きインタラクティブ製品コンフィギュレーターの作成",
    fr: "Création d'un configurateur de produit interactif avec capacités de prévisualisation 3D",
  },
  {
    en: "Integrated fraud detection service using machine learning models",
    ar: "دمج خدمة كشف الاحتيال باستخدام نماذج التعلم الآلي",
    ja: "機械学習モデルを使用した不正検知サービスの統合",
    fr: "Intégration d'un service de détection de fraude avec des modèles d'apprentissage automatique",
  },
  {
    en: "Developed offline-first mobile application with PouchDB synchronization",
    ar: "تطوير تطبيق هاتف محمول يعمل دون اتصال أولاً مع مزامنة PouchDB",
    ja: "PouchDB同期付きオフライン優先モバイルアプリケーションの開発",
    fr: "Développement d'une application mobile offline-first avec synchronisation PouchDB",
  },
  {
    en: "Implemented multi-tenant architecture supporting custom domains per customer",
    ar: "تنفيذ هندسة متعددة المستأجرين تدعم النطاقات المخصصة لكل عميل",
    ja: "顧客ごとのカスタムドメイン対応マルチテナントアーキテクチャの実装",
    fr: "Implémentation d'une architecture multi-tenant prenant en charge les domaines personnalisés par client",
  },
  {
    en: "Optimized build pipeline reducing CI time from 18 minutes to 4 minutes",
    ar: "تحسين خط الأنابيب البناء مما قلل وقت CI من 18 دقيقة إلى 4 دقائق",
    ja: "CI時間を18分から4分に短縮するビルドパイプラインの最適化",
    fr: "Optimisation du pipeline de build réduisant le temps CI de 18 minutes à 4 minutes",
  },
  {
    en: "Created comprehensive error monitoring dashboard with Sentry integration",
    ar: "إنشاء لوحة تحكم مراقبة أخطاء شاملة مع تكامل Sentry",
    ja: "Sentry統合付き包括的なエラーモニタリングダッシュボードの作成",
    fr: "Création d'un tableau de bord complet de surveillance des erreurs avec intégration Sentry",
  },
  {
    en: "Implemented progressive web app (PWA) features for enhanced mobile experience",
    ar: "تنفيذ ميزات التطبيق الويب التقدمي (PWA) لتجربة محمولة محسنة",
    ja: "強化されたモバイル体験のためのプログレッシブウェブアプリ（PWA）機能の実装",
    fr: "Implémentation des fonctionnalités d'application web progressive (PWA) pour une expérience mobile améliorée",
  },
  {
    en: "Developed automated translation service using DeepL API for content localization",
    ar: "تطوير خدمة ترجمة آلية باستخدام DeepL API لتوطين المحتوى",
    ja: "コンテンツローカライズ用DeepL API自動翻訳サービスの開発",
    fr: "Développement d'un service de traduction automatique avec l'API DeepL pour la localisation du contenu",
  },
  {
    en: "Integrated loyalty program engine with points tracking and redemption system",
    ar: "دمج محرك برنامج الولاء مع تتبع النقاط ونظام الاسترداد",
    ja: "ポイント追跡と交換システム付きロイヤリティプログラムエンジンの統合",
    fr: "Intégration d'un moteur de programme de fidélité avec suivi des points et système de rachat",
  },
  {
    en: "Optimized frontend state management using Zustand and TanStack Query",
    ar: "تحسين إدارة حالة الواجهة الأمامية باستخدام Zustand و TanStack Query",
    ja: "ZustandとTanStack Queryを使用したフロントエンド状態管理の最適化",
    fr: "Optimisation de la gestion d'état frontend avec Zustand et TanStack Query",
  },
  {
    en: "Implemented secure file sharing with expiration and password protection",
    ar: "تنفيذ مشاركة ملفات آمنة مع انتهاء الصلاحية وحماية كلمة المرور",
    ja: "有効期限とパスワード保護付きセキュアファイル共有の実装",
    fr: "Implémentation du partage de fichiers sécurisé avec expiration et protection par mot de passe",
  },
  {
    en: "Developed custom CRM dashboard with pipeline visualization and forecasting",
    ar: "تطوير لوحة تحكم CRM مخصصة مع تصور خط الأنابيب والتنبؤ",
    ja: "パイプライン可視化と予測付きカスタムCRMダッシュボードの開発",
    fr: "Développement d'un tableau de bord CRM personnalisé avec visualisation du pipeline et prévision",
  },
  {
    en: "Created automated compliance reporting for GDPR and SOC 2 requirements",
    ar: "إنشاء تقارير امتثال آلية لمتطلبات GDPR و SOC 2",
    ja: "GDPRとSOC 2要件対応の自動コンプライアンスレポート作成",
    fr: "Création de rapports de conformité automatisés pour les exigences GDPR et SOC 2",
  },
];

export const SKILLSPOOL = [
  "javascript",
  "typescript",
  "html",
  "css",
  "sql",
  "react",
  "vue",
  "angular",
  "redux",
  "next.js",
  "tailwind",
  "node.js",
  "express",
  "nestjs",
  "mongodb",
  "postgresql",
  "mysql",
];

export const LOCATIONS = ["us", "fr", "ma", "ja", "uk", "sp"];

export const INTERVIEWSTEPS = [
  "hr",
  "interview1",
  "interview2",
  "systemDesign",
  "culturalFit",
  "ceo",
];

export const POSITIONS = [
  "front",
  "backend",
  "design",
  "fullStack",
  "data",
  "c++",
  "php",
  "django",
  "project",
  "devOps",
  "cloud",
];

export const DEPARTMENTS = [
  "development",
  "sales",
  "management",
  "analytics",
  "finance",
  "hr",
  "data",
];

export const PHONENUMBERS = {
  us: [
    "+1 (212) 555-0142",
    "+1 (310) 555-2389",
    "+1 (415) 555-6721",
    "+1 (312) 555-9834",
    "+1 (702) 555-1765",
    "+1 (206) 555-4498",
    "+1 (617) 555-7321",
    "+1 (305) 555-8901",
    "+1 (713) 555-2345",
    "+1 (214) 555-6789",
    "+1 (602) 555-1123",
    "+1 (303) 555-4456",
    "+1 (512) 555-7789",
    "+1 (404) 555-0012",
    "+1 (702) 555-3345",
    "+1 (415) 555-5567",
    "+1 (212) 555-8890",
    "+1 (310) 555-1234",
    "+1 (206) 555-5678",
    "+1 (617) 555-9012",
    "+1 (305) 555-3456",
    "+1 (713) 555-7890",
    "+1 (214) 555-2345",
    "+1 (602) 555-6789",
    "+1 (303) 555-0123",
  ],
  fr: [
    "+33 1 42 68 45 12",
    "+33 1 53 67 89 01",
    "+33 2 47 85 12 34",
    "+33 3 20 45 67 89",
    "+33 4 91 23 45 67",
    "+33 5 55 67 89 01",
    "+33 6 12 34 56 78",
    "+33 6 78 90 12 34",
    "+33 7 45 67 89 01",
    "+33 1 45 67 89 12",
    "+33 1 48 52 63 74",
    "+33 2 98 76 54 32",
    "+33 3 88 45 67 89",
    "+33 4 72 34 56 78",
    "+33 5 61 23 45 67",
    "+33 6 23 45 67 89",
    "+33 7 89 01 23 45",
    "+33 1 55 66 77 88",
    "+33 2 40 12 34 56",
    "+33 3 29 87 65 43",
    "+33 4 93 45 67 89",
    "+33 5 34 56 78 90",
    "+33 6 45 67 89 01",
    "+33 7 12 34 56 78",
    "+33 1 44 55 66 77",
  ],
  ma: [
    "+212 522 345 678",
    "+212 523 456 789",
    "+212 524 567 890",
    "+212 525 678 901",
    "+212 528 789 012",
    "+212 529 890 123",
    "+212 530 901 234",
    "+212 531 012 345",
    "+212 532 123 456",
    "+212 533 234 567",
    "+212 534 345 678",
    "+212 535 456 789",
    "+212 536 567 890",
    "+212 537 678 901",
    "+212 538 789 012",
    "+212 539 890 123",
    "+212 660 123 456",
    "+212 661 234 567",
    "+212 662 345 678",
    "+212 663 456 789",
    "+212 664 567 890",
    "+212 665 678 901",
    "+212 666 789 012",
    "+212 667 890 123",
    "+212 668 901 234",
  ],
  ja: [
    "+81 3-1234-5678",
    "+81 6-2345-6789",
    "+81 11-3456-7890",
    "+81 52-4567-8901",
    "+81 92-5678-9012",
    "+81 75-6789-0123",
    "+81 82-7890-1234",
    "+81 98-8901-2345",
    "+81 45-9012-3456",
    "+81 78-0123-4567",
    "+81 3-2345-6789",
    "+81 6-3456-7890",
    "+81 11-4567-8901",
    "+81 52-5678-9012",
    "+81 92-6789-0123",
    "+81 75-7890-1234",
    "+81 82-8901-2345",
    "+81 98-9012-3456",
    "+81 45-0123-4567",
    "+81 78-1234-5678",
    "+81 3-3456-7890",
    "+81 6-4567-8901",
    "+81 11-5678-9012",
    "+81 52-6789-0123",
    "+81 92-7890-1234",
  ],
  uk: [
    "+44 20 7946 0958",
    "+44 121 496 0123",
    "+44 131 496 0456",
    "+44 151 496 0789",
    "+44 161 496 0123",
    "+44 20 7946 1234",
    "+44 115 496 5678",
    "+44 141 496 9012",
    "+44 113 496 3456",
    "+44 117 496 7890",
    "+44 20 7946 2345",
    "+44 121 496 6789",
    "+44 131 496 0123",
    "+44 151 496 3456",
    "+44 161 496 6789",
    "+44 20 7946 8901",
    "+44 115 496 2345",
    "+44 141 496 5678",
    "+44 113 496 9012",
    "+44 117 496 1234",
    "+44 20 7946 4567",
    "+44 121 496 8901",
    "+44 131 496 2345",
    "+44 151 496 5678",
    "+44 161 496 9012",
  ],
  sp: [
    "+34 91 234 5678",
    "+34 93 456 7890",
    "+34 95 678 9012",
    "+34 96 123 4567",
    "+34 97 345 6789",
    "+34 98 567 8901",
    "+34 600 123 456",
    "+34 612 345 678",
    "+34 623 456 789",
    "+34 634 567 890",
    "+34 645 678 901",
    "+34 656 789 012",
    "+34 667 890 123",
    "+34 678 901 234",
    "+34 689 012 345",
    "+34 91 345 6789",
    "+34 93 567 8901",
    "+34 95 789 0123",
    "+34 96 901 2345",
    "+34 97 123 4567",
    "+34 98 234 5678",
    "+34 610 234 567",
    "+34 621 345 678",
    "+34 632 456 789",
    "+34 643 567 890",
  ],
};

export const ALPHABETS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

export const ACTIVEPROJECTS = [
  {
    en: {
      projTitle: "E-Commerce Platform Redesign - Phase 1",
      projDesc:
        "Complete overhaul of the user interface and backend integration for the main online store to improve conversion rates and mobile responsiveness.",
      deadline: new Date("2026-08-25"),
      projLeader: "Sarah Chen",
      progress: 35,
    },
    ja: {
      projTitle: "ECプラットフォームの再設計 - Phase 1",
      projDesc:
        "メインオンラインストアのユーザーインターフェースとバックエンド統合を全面的に刷新し、コンバージョン率とモバイル対応を向上させる。",
      deadline: new Date("2026-08-25"),
      projLeader: "Sarah Chen",
      progress: 35,
    },
    ar: {
      projTitle: "إعادة تصميم منصة التجارة الإلكترونية - Phase 1",
      projDesc:
        "إعادة تصميم شاملة لواجهة المستخدم والتكامل الخلفي للمتجر الإلكتروني الرئيسي لتحسين معدلات التحويل والاستجابة للأجهزة المحمولة.",
      deadline: new Date("2026-08-25"),
      projLeader: "Sarah Chen",
      progress: 35,
    },
    fr: {
      projTitle: "Refonte de la Plateforme E-Commerce - Phase 1",
      projDesc:
        "Refonte complète de l'interface utilisateur et de l'intégration backend de la boutique en ligne principale afin d'améliorer les taux de conversion et la réactivité mobile.",
      deadline: new Date("2026-08-25"),
      projLeader: "Sarah Chen",
      progress: 35,
    },
  },
  {
    en: {
      projTitle: "Mobile Banking App Enhancement",
      projDesc:
        "Implementation of biometric authentication and real-time transaction notifications for the consumer banking application.",
      deadline: new Date("2026-10-05"),
      projLeader: "Ahmed Khalil",
      progress: 82,
    },
    ja: {
      projTitle: "モバイルバンキングアプリの強化",
      projDesc:
        "消費者向けバンキングアプリケーションに生体認証とリアルタイム取引通知を実装する。",
      deadline: new Date("2026-10-05"),
      projLeader: "Ahmed Khalil",
      progress: 82,
    },
    ar: {
      projTitle: "تعزيز تطبيق الخدمات المصرفية المتنقلة",
      projDesc:
        "تنفيذ المصادقة البيومترية وإشعارات المعاملات في الوقت الفعلي لتطبيق الخدمات المصرفية للمستهلكين.",
      deadline: new Date("2026-10-05"),
      projLeader: "Ahmed Khalil",
      progress: 82,
    },
    fr: {
      projTitle: "Amélioration de l'Application Bancaire Mobile",
      projDesc:
        "Implémentation de l'authentification biométrique et des notifications de transactions en temps réel pour l'application bancaire grand public.",
      deadline: new Date("2026-10-05"),
      projLeader: "Ahmed Khalil",
      progress: 82,
    },
  },
  {
    en: {
      projTitle: "Hospital Patient Management System",
      projDesc:
        "Development of a new digital system to streamline patient admissions, records, and discharge processes in a major hospital network.",
      deadline: new Date("2027-02-07"),
      projLeader: "Dr. Fatima El Amrani",
      progress: 11,
    },
    ja: {
      projTitle: "病院患者管理システム",
      projDesc:
        "主要病院ネットワークにおける患者の入院、記録、退院プロセスを合理化する新しいデジタルシステムの開発。",
      deadline: new Date("2027-02-07"),
      projLeader: "Dr. Fatima El Amrani",
      progress: 11,
    },
    ar: {
      projTitle: "نظام إدارة مرضى المستشفى",
      projDesc:
        "تطوير نظام رقمي جديد لتبسيط عمليات قبول المرضى وسجلاتهم والتسريح في شبكة مستشفيات كبرى.",
      deadline: new Date("2027-02-07"),
      projLeader: "Dr. Fatima El Amrani",
      progress: 11,
    },
    fr: {
      projTitle: "Système de Gestion des Patients Hospitaliers",
      projDesc:
        "Développement d'un nouveau système numérique pour rationaliser les admissions, les dossiers et les processus de sortie des patients dans un réseau hospitalier majeur.",
      deadline: new Date("2027-02-07"),
      projLeader: "Dr. Fatima El Amrani",
      progress: 11,
    },
  },
  {
    en: {
      projTitle: "Corporate Website Localization",
      projDesc:
        "Translation and cultural adaptation of the company website into Japanese, Arabic, and French markets with SEO optimization.",
      deadline: new Date("2027-01-30"),
      projLeader: "Pierre Laurent",
      progress: 79,
    },
    ja: {
      projTitle: "企業ウェブサイトのローカライズ",
      projDesc:
        "日本語、アラビア語、フランス語市場向けに企業ウェブサイトを翻訳・文化適応し、SEOを最適化する。",
      deadline: new Date("2027-01-30"),
      projLeader: "Pierre Laurent",
      progress: 79,
    },
    ar: {
      projTitle: "توطين موقع الشركة الإلكتروني",
      projDesc:
        "ترجمة وتكييف ثقافي لموقع الشركة الإلكتروني إلى أسواق اليابان والعربية والفرنسية مع تحسين محركات البحث.",
      deadline: new Date("2027-01-30"),
      projLeader: "Pierre Laurent",
      progress: 79,
    },
    fr: {
      projTitle: "Localisation du Site Web d'Entreprise",
      projDesc:
        "Traduction et adaptation culturelle du site web de l'entreprise vers les marchés japonais, arabe et français avec optimisation SEO.",
      deadline: new Date("2027-01-30"),
      projLeader: "Pierre Laurent",
      progress: 79,
    },
  },
  {
    en: {
      projTitle: "Supply Chain Optimization Tool",
      projDesc:
        "Implementation of an AI-driven dashboard to forecast demand and optimize logistics routes for a global manufacturing firm.",
      deadline: new Date("2026-09-05"),
      projLeader: "Kenji Takahashi",
      progress: 57,
    },
    ja: {
      projTitle: "サプライチェーン最適化ツール",
      projDesc:
        "グローバル製造企業向けに需要予測と物流ルート最適化を行うAI駆動型ダッシュボードの実装。",
      deadline: new Date("2026-09-05"),
      projLeader: "Kenji Takahashi",
      progress: 57,
    },
    ar: {
      projTitle: "أداة تحسين سلسلة التوريد",
      projDesc:
        "تنفيذ لوحة تحكم مدعومة بالذكاء الاصطناعي للتنبؤ بالطلب وتحسين مسارات اللوجستيات لشركة تصنيع عالمية.",
      deadline: new Date("2026-09-05"),
      projLeader: "Kenji Takahashi",
      progress: 57,
    },
    fr: {
      projTitle: "Outil d'Optimisation de la Chaîne d'Approvisionnement",
      projDesc:
        "Implémentation d'un tableau de bord piloté par IA pour prévoir la demande et optimiser les itinéraires logistiques pour une entreprise manufacturière mondiale.",
      deadline: new Date("2026-09-05"),
      projLeader: "Kenji Takahashi",
      progress: 57,
    },
  },
  {
    en: {
      projTitle: "University Online Learning Platform Upgrade",
      projDesc:
        "Migration to a new LMS with enhanced video streaming, assessment tools, and accessibility features for 50,000+ students.",
      deadline: new Date("2027-01-12"),
      projLeader: "Prof. Aisha Rahman",
      progress: 61,
    },
    ja: {
      projTitle: "大学オンライン学習プラットフォームのアップグレード",
      projDesc:
        "5万人以上の学生向けに、強化されたビデオストリーミング、評価ツール、アクセシビリティ機能を備えた新しいLMSへの移行。",
      deadline: new Date("2027-01-12"),
      projLeader: "Prof. Aisha Rahman",
      progress: 61,
    },
    ar: {
      projTitle: "ترقية منصة التعلم عبر الإنترネット بالجامعة",
      projDesc:
        "الانتقال إلى نظام إدارة التعلم الجديد مع تحسينات في بث الفيديو وأدوات التقييم وميزات الوصولية لأكثر من 50,000 طالب.",
      deadline: new Date("2027-01-12"),
      projLeader: "Prof. Aisha Rahman",
      progress: 61,
    },
    fr: {
      projTitle:
        "Mise à Niveau de la Plateforme d'Apprentissage en Ligne Universitaire",
      projDesc:
        "Migration vers un nouveau LMS avec diffusion vidéo améliorée, outils d'évaluation et fonctionnalités d'accessibilité pour plus de 50 000 étudiants.",
      deadline: new Date("2027-01-12"),
      projLeader: "Prof. Aisha Rahman",
      progress: 61,
    },
  },
  {
    en: {
      projTitle: "Renewable Energy Grid Integration",
      projDesc:
        "Engineering study and pilot deployment of solar and wind integration into the national electricity grid in selected regions.",
      deadline: new Date("2027-08-06"),
      projLeader: "Jean Moreau",
      progress: 40,
    },
    ja: {
      projTitle: "再生可能エネルギーグリッド統合",
      projDesc:
        "選定地域における太陽光と風力の国家電力グリッドへの統合に関するエンジニアリング調査とパイロット展開。",
      deadline: new Date("2027-08-06"),
      projLeader: "Jean Moreau",
      progress: 40,
    },
    ar: {
      projTitle: "دمج شبكة الطاقة المتجددة",
      projDesc:
        "دراسة هندسية ونشر تجريبي لدمج الطاقة الشمسية والرياح في شبكة الكهرباء الوطنية في مناطق مختارة.",
      deadline: new Date("2027-08-06"),
      projLeader: "Jean Moreau",
      progress: 40,
    },
    fr: {
      projTitle: "Intégration au Réseau des Énergies Renouvelables",
      projDesc:
        "Étude d'ingénierie et déploiement pilote de l'intégration solaire et éolienne dans le réseau électrique national dans des régions sélectionnées.",
      deadline: new Date("2027-08-06"),
      projLeader: "Jean Moreau",
      progress: 40,
    },
  },
  {
    en: {
      projTitle: "HR Digital Transformation Initiative",
      projDesc:
        "Implementation of a unified HRIS platform covering recruitment, performance management, and payroll across all international offices.",
      deadline: new Date("2027-02-08"),
      projLeader: "Maria Gonzalez",
      progress: 10,
    },
    ja: {
      projTitle: "人事デジタルトランスフォーメーションイニシアチブ",
      projDesc:
        "全国際オフィスを対象とした採用、パフォーマンス管理、給与計算をカバーする統一HRISプラットフォームの実装。",
      deadline: new Date("2027-02-08"),
      projLeader: "Maria Gonzalez",
      progress: 10,
    },
    ar: {
      projTitle: "مبادرة التحول الرقمي للموارد البشرية",
      projDesc:
        "تنفيذ منصة موارد بشرية موحدة تغطي التوظيف وإدارة الأداء والرواتب عبر جميع المكاتب الدولية.",
      deadline: new Date("2027-02-08"),
      projLeader: "Maria Gonzalez",
      progress: 10,
    },
    fr: {
      projTitle: "Initiative de Transformation Numérique des RH",
      projDesc:
        "Implémentation d'une plateforme SIRH unifiée couvrant le recrutement, la gestion des performances et la paie dans tous les bureaux internationaux.",
      deadline: new Date("2027-02-08"),
      projLeader: "Maria Gonzalez",
      progress: 10,
    },
  },
  {
    en: {
      projTitle: "AI-Powered Customer Support Chatbot",
      projDesc:
        "Development and deployment of a multilingual AI chatbot to handle 70% of tier-1 customer inquiries for the retail division.",
      deadline: new Date("2026-11-12"),
      projLeader: "Liam Dubois",
      progress: 89,
    },
    ja: {
      projTitle: "AI搭載カスタマーサポートチャットボット",
      projDesc:
        "小売部門のティア1顧客問い合わせの70%を処理する多言語AIチャットボットの開発と展開。",
      deadline: new Date("2026-11-12"),
      projLeader: "Liam Dubois",
      progress: 89,
    },
    ar: {
      projTitle: "روبوت دردشة دعم العملاء مدعوم بالذكاء الاصطناعي",
      projDesc:
        "تطوير ونشر روبوت دردشة ذكي متعدد اللغات للتعامل مع 70% من استفسارات العملاء من المستوى الأول في قسم التجزئة.",
      deadline: new Date("2026-11-12"),
      projLeader: "Liam Dubois",
      progress: 89,
    },
    fr: {
      projTitle: "Chatbot de Support Client Alimenté par l'IA",
      projDesc:
        "Développement et déploiement d'un chatbot IA multilingue pour traiter 70 % des demandes de support client de niveau 1 pour la division retail.",
      deadline: new Date("2026-11-12"),
      projLeader: "Liam Dubois",
      progress: 89,
    },
  },
  {
    en: {
      projTitle: "Smart City Traffic Management System",
      projDesc:
        "Installation of IoT sensors and AI analytics to optimize traffic flow and reduce congestion in downtown areas.",
      deadline: new Date("2027-10-01"),
      projLeader: "Omar Benali",
      progress: 34,
    },
    ja: {
      projTitle: "スマートシティ交通管理システム",
      projDesc:
        "IoTセンサーとAI分析を導入し、ダウンタウン地域の交通流を最適化して渋滞を削減する。",
      deadline: new Date("2027-10-01"),
      projLeader: "Omar Benali",
      progress: 34,
    },
    ar: {
      projTitle: "نظام إدارة حركة المرور في المدينة الذكية",
      projDesc:
        "تركيب أجهزة استشعار إنترنت الأشياء وتحليلات الذكاء الاصطناعي لتحسين تدفق المرور وتقليل الازدحام في مناطق وسط المدينة.",
      deadline: new Date("2027-10-01"),
      projLeader: "Omar Benali",
      progress: 34,
    },
    fr: {
      projTitle: "Système de Gestion du Trafic pour Ville Intelligente",
      projDesc:
        "Installation de capteurs IoT et d'analyses IA pour optimiser le flux de trafic et réduire les embouteillages dans les zones du centre-ville.",
      deadline: new Date("2027-10-01"),
      projLeader: "Omar Benali",
      progress: 34,
    },
  },
];
