export const enNotifications = [
  {
    id: 1,
    title: "New message from support",
    read: false,
    readAt: null,
  },
  {
    id: 2,
    title: "Your password was updated successfully",
    read: true,
    readAt: "2026-02-20T09:15:00Z",
  },
  {
    id: 3,
    title: "New login detected from Chrome on Linux",
    read: true,
    readAt: "2026-02-18T18:42:31Z",
  },
  {
    id: 4,
    title: "Weekly activity summary is ready",
    read: false,
    readAt: null,
  },
  {
    id: 5,
    title: "Payment received for invoice #4821",
    read: true,
    readAt: "2026-02-17T14:03:12Z",
  },
  {
    id: 6,
    title: "Subscription will renew in 3 days",
    read: false,
    readAt: null,
  },
  {
    id: 7,
    title: "New comment on your post",
    read: true,
    readAt: "2026-02-16T11:27:45Z",
  },
  {
    id: 8,
    title: "Two-factor authentication enabled",
    read: true,
    readAt: "2026-02-15T20:10:05Z",
  },
  {
    id: 9,
    title: "Storage usage is nearing limit",
    read: false,
    readAt: null,
  },
  {
    id: 10,
    title: "Profile information updated",
    read: true,
    readAt: "2026-02-14T08:55:19Z",
  },
  {
    id: 11,
    title: "New device connected to your account",
    read: false,
    readAt: null,
  },
  {
    id: 12,
    title: "Maintenance scheduled for this weekend",
    read: true,
    readAt: "2026-02-13T16:22:48Z",
  },
];

export const jaNotifications = [
  { id: 1, title: "サポートからの新しいメッセージ", read: false, readAt: null },
  {
    id: 2,
    title: "パスワードが正常に更新されました",
    read: true,
    readAt: "2026-02-20T09:15:00Z",
  },
  {
    id: 3,
    title: "Linux上のChromeからの新しいログインが検出されました",
    read: true,
    readAt: "2026-02-18T18:42:31Z",
  },
  {
    id: 4,
    title: "週間アクティビティの概要が準備できました",
    read: false,
    readAt: null,
  },
  {
    id: 5,
    title: "請求書 #4821 の支払いを受け取りました",
    read: true,
    readAt: "2026-02-17T14:03:12Z",
  },
  {
    id: 6,
    title: "サブスクリプションは3日後に更新されます",
    read: false,
    readAt: null,
  },
  {
    id: 7,
    title: "あなたの投稿に新しいコメントがあります",
    read: true,
    readAt: "2026-02-16T11:27:45Z",
  },
  {
    id: 8,
    title: "二段階認証が有効になりました",
    read: true,
    readAt: "2026-02-15T20:10:05Z",
  },
  {
    id: 9,
    title: "ストレージの使用量が上限に近づいています",
    read: false,
    readAt: null,
  },
  {
    id: 10,
    title: "プロフィール情報が更新されました",
    read: true,
    readAt: "2026-02-14T08:55:19Z",
  },
  {
    id: 11,
    title: "新しいデバイスがあなたのアカウントに接続されました",
    read: false,
    readAt: null,
  },
  {
    id: 12,
    title: "今週末にメンテナンスが予定されています",
    read: true,
    readAt: "2026-02-13T16:22:48Z",
  },
];

export const arNotifications = [
  { id: 1, title: "رسالة جديدة من الدعم", read: false, readAt: null },
  {
    id: 2,
    title: "تم تحديث كلمة المرور بنجاح",
    read: true,
    readAt: "2026-02-20T09:15:00Z",
  },
  {
    id: 3,
    title: "تم اكتشاف تسجيل دخول جديد من Chrome على Linux",
    read: true,
    readAt: "2026-02-18T18:42:31Z",
  },
  { id: 4, title: "ملخص النشاط الأسبوعي جاهز", read: false, readAt: null },
  {
    id: 5,
    title: "تم استلام الدفع للفاتورة رقم #4821",
    read: true,
    readAt: "2026-02-17T14:03:12Z",
  },
  {
    id: 6,
    title: "سيتم تجديد الاشتراك خلال 3 أيام",
    read: false,
    readAt: null,
  },
  {
    id: 7,
    title: "تعليق جديد على منشورك",
    read: true,
    readAt: "2026-02-16T11:27:45Z",
  },
  {
    id: 8,
    title: "تم تفعيل المصادقة الثنائية",
    read: true,
    readAt: "2026-02-15T20:10:05Z",
  },
  {
    id: 9,
    title: "استخدام التخزين يقترب من الحد الأقصى",
    read: false,
    readAt: null,
  },
  {
    id: 10,
    title: "تم تحديث معلومات الملف الشخصي",
    read: true,
    readAt: "2026-02-14T08:55:19Z",
  },
  { id: 11, title: "تم توصيل جهاز جديد بحسابك", read: false, readAt: null },
  {
    id: 12,
    title: "تمت جدولة صيانة في عطلة نهاية الأسبوع",
    read: true,
    readAt: "2026-02-13T16:22:48Z",
  },
];

export const frNotifications = [
  { id: 1, title: "Nouveau message du support", read: false, readAt: null },
  {
    id: 2,
    title: "Votre mot de passe a été mis à jour avec succès",
    read: true,
    readAt: "2026-02-20T09:15:00Z",
  },
  {
    id: 3,
    title: "Nouvelle connexion détectée depuis Chrome sur Linux",
    read: true,
    readAt: "2026-02-18T18:42:31Z",
  },
  {
    id: 4,
    title: "Le résumé d’activité hebdomadaire est prêt",
    read: false,
    readAt: null,
  },
  {
    id: 5,
    title: "Paiement reçu pour la facture n°4821",
    read: true,
    readAt: "2026-02-17T14:03:12Z",
  },
  {
    id: 6,
    title: "L’abonnement sera renouvelé dans 3 jours",
    read: false,
    readAt: null,
  },
  {
    id: 7,
    title: "Nouveau commentaire sur votre publication",
    read: true,
    readAt: "2026-02-16T11:27:45Z",
  },
  {
    id: 8,
    title: "Authentification à deux facteurs activée",
    read: true,
    readAt: "2026-02-15T20:10:05Z",
  },
  {
    id: 9,
    title: "L’espace de stockage approche de la limite",
    read: false,
    readAt: null,
  },
  {
    id: 10,
    title: "Informations du profil mises à jour",
    read: true,
    readAt: "2026-02-14T08:55:19Z",
  },
  {
    id: 11,
    title: "Un nouvel appareil est connecté à votre compte",
    read: false,
    readAt: null,
  },
  {
    id: 12,
    title: "Maintenance prévue ce week-end",
    read: true,
    readAt: "2026-02-13T16:22:48Z",
  },
];

export const candidates = [
  {
    id: 1,
    name: "Emma Johnson",
    position: "Frontend Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 2,
    name: "Liam Smith",
    position: "Backend Developer",
    offerState: "PENDING",
  },
  {
    id: 3,
    name: "Olivia Brown",
    position: "UI/UX Designer",
    offerState: "OFFER",
  },
  {
    id: 4,
    name: "Noah Garcia",
    position: "DevOps Engineer",
    offerState: "REJECT",
  },
  {
    id: 5,
    name: "Ava Martinez",
    position: "QA Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 6,
    name: "William Davis",
    position: "Full Stack Developer",
    offerState: "PENDING",
  },
  {
    id: 7,
    name: "Sophia Rodriguez",
    position: "Product Manager",
    offerState: "OFFER",
  },
  {
    id: 8,
    name: "James Wilson",
    position: "Data Analyst",
    offerState: "REJECT",
  },
  {
    id: 9,
    name: "Isabella Anderson",
    position: "Mobile Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 10,
    name: "Benjamin Thomas",
    position: "Cloud Engineer",
    offerState: "PENDING",
  },
  {
    id: 11,
    name: "Mia Taylor",
    position: "Frontend Developer",
    offerState: "OFFER",
  },
  {
    id: 12,
    name: "Lucas Moore",
    position: "Backend Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 13,
    name: "Charlotte Jackson",
    position: "HR Specialist",
    offerState: "REJECT",
  },
  {
    id: 14,
    name: "Henry Martin",
    position: "Security Engineer",
    offerState: "PENDING",
  },
  {
    id: 15,
    name: "Amelia Lee",
    position: "UI/UX Designer",
    offerState: "SHORTLIST",
  },
  {
    id: 16,
    name: "Alexander Perez",
    position: "Data Scientist",
    offerState: "OFFER",
  },
  {
    id: 17,
    name: "Harper Thompson",
    position: "Scrum Master",
    offerState: "PENDING",
  },
  {
    id: 18,
    name: "Daniel White",
    position: "QA Engineer",
    offerState: "REJECT",
  },
  {
    id: 19,
    name: "Evelyn Harris",
    position: "Full Stack Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 20,
    name: "Michael Sanchez",
    position: "DevOps Engineer",
    offerState: "OFFER",
  },
  {
    id: 21,
    name: "Abigail Clark",
    position: "Frontend Developer",
    offerState: "PENDING",
  },
  {
    id: 22,
    name: "Matthew Ramirez",
    position: "Backend Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 23,
    name: "Emily Lewis",
    position: "Product Manager",
    offerState: "REJECT",
  },
  {
    id: 24,
    name: "David Robinson",
    position: "Cloud Engineer",
    offerState: "OFFER",
  },
  {
    id: 25,
    name: "Ella Walker",
    position: "UI/UX Designer",
    offerState: "SHORTLIST",
  },
  {
    id: 26,
    name: "Joseph Young",
    position: "Mobile Developer",
    offerState: "PENDING",
  },
  {
    id: 27,
    name: "Avery Allen",
    position: "Data Analyst",
    offerState: "REJECT",
  },
  {
    id: 28,
    name: "Samuel King",
    position: "Security Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 29,
    name: "Scarlett Wright",
    position: "QA Engineer",
    offerState: "OFFER",
  },
  {
    id: 30,
    name: "Sebastian Scott",
    position: "Full Stack Developer",
    offerState: "PENDING",
  },

  {
    id: 31,
    name: "Grace Green",
    position: "Frontend Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 32,
    name: "Jack Baker",
    position: "Backend Developer",
    offerState: "REJECT",
  },
  {
    id: 33,
    name: "Chloe Adams",
    position: "Data Scientist",
    offerState: "OFFER",
  },
  {
    id: 34,
    name: "Owen Nelson",
    position: "DevOps Engineer",
    offerState: "PENDING",
  },
  {
    id: 35,
    name: "Lily Carter",
    position: "Product Manager",
    offerState: "SHORTLIST",
  },
  {
    id: 36,
    name: "Gabriel Mitchell",
    position: "Cloud Engineer",
    offerState: "REJECT",
  },
  {
    id: 37,
    name: "Zoey Perez",
    position: "UI/UX Designer",
    offerState: "OFFER",
  },
  {
    id: 38,
    name: "Carter Roberts",
    position: "QA Engineer",
    offerState: "PENDING",
  },
  {
    id: 39,
    name: "Riley Turner",
    position: "Full Stack Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 40,
    name: "Julian Phillips",
    position: "Mobile Developer",
    offerState: "REJECT",
  },

  {
    id: 41,
    name: "Nora Campbell",
    position: "Frontend Developer",
    offerState: "OFFER",
  },
  {
    id: 42,
    name: "Isaac Parker",
    position: "Backend Developer",
    offerState: "PENDING",
  },
  {
    id: 43,
    name: "Hannah Evans",
    position: "HR Specialist",
    offerState: "SHORTLIST",
  },
  {
    id: 44,
    name: "Anthony Edwards",
    position: "Security Engineer",
    offerState: "REJECT",
  },
  {
    id: 45,
    name: "Aria Collins",
    position: "Data Analyst",
    offerState: "OFFER",
  },
  {
    id: 46,
    name: "Christopher Stewart",
    position: "DevOps Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 47,
    name: "Layla Morris",
    position: "UI/UX Designer",
    offerState: "PENDING",
  },
  {
    id: 48,
    name: "Andrew Rogers",
    position: "Full Stack Developer",
    offerState: "REJECT",
  },
  {
    id: 49,
    name: "Camila Reed",
    position: "Product Manager",
    offerState: "SHORTLIST",
  },
  { id: 50, name: "Joshua Cook", position: "QA Engineer", offerState: "OFFER" },

  {
    id: 51,
    name: "Victoria Morgan",
    position: "Cloud Engineer",
    offerState: "PENDING",
  },
  {
    id: 52,
    name: "Nathan Bell",
    position: "Frontend Developer",
    offerState: "REJECT",
  },
  {
    id: 53,
    name: "Madison Murphy",
    position: "Backend Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 54,
    name: "Ryan Bailey",
    position: "Data Scientist",
    offerState: "OFFER",
  },
  {
    id: 55,
    name: "Zoe Rivera",
    position: "Mobile Developer",
    offerState: "PENDING",
  },
  {
    id: 56,
    name: "Aaron Cooper",
    position: "DevOps Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 57,
    name: "Penelope Richardson",
    position: "UI/UX Designer",
    offerState: "REJECT",
  },
  {
    id: 58,
    name: "Adam Cox",
    position: "Security Engineer",
    offerState: "OFFER",
  },
  {
    id: 59,
    name: "Stella Howard",
    position: "Product Manager",
    offerState: "PENDING",
  },
  {
    id: 60,
    name: "Thomas Ward",
    position: "QA Engineer",
    offerState: "SHORTLIST",
  },

  // Continuing same structure up to 150

  {
    id: 61,
    name: "Lucy Torres",
    position: "Frontend Developer",
    offerState: "OFFER",
  },
  {
    id: 62,
    name: "Charles Peterson",
    position: "Backend Developer",
    offerState: "PENDING",
  },
  {
    id: 63,
    name: "Paisley Gray",
    position: "Cloud Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 64,
    name: "Isaiah Ramirez",
    position: "Data Analyst",
    offerState: "REJECT",
  },
  {
    id: 65,
    name: "Violet James",
    position: "UI/UX Designer",
    offerState: "OFFER",
  },
  {
    id: 66,
    name: "Josiah Watson",
    position: "Full Stack Developer",
    offerState: "PENDING",
  },
  {
    id: 67,
    name: "Claire Brooks",
    position: "QA Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 68,
    name: "Eli Kelly",
    position: "DevOps Engineer",
    offerState: "REJECT",
  },
  {
    id: 69,
    name: "Skylar Sanders",
    position: "Product Manager",
    offerState: "OFFER",
  },
  {
    id: 70,
    name: "Christian Price",
    position: "Mobile Developer",
    offerState: "PENDING",
  },

  {
    id: 71,
    name: "Bella Bennett",
    position: "Frontend Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 72,
    name: "Jonathan Wood",
    position: "Backend Developer",
    offerState: "REJECT",
  },
  {
    id: 73,
    name: "Aurora Barnes",
    position: "Security Engineer",
    offerState: "OFFER",
  },
  {
    id: 74,
    name: "Colton Ross",
    position: "Cloud Engineer",
    offerState: "PENDING",
  },
  {
    id: 75,
    name: "Naomi Henderson",
    position: "Data Scientist",
    offerState: "SHORTLIST",
  },

  {
    id: 76,
    name: "Robert Coleman",
    position: "QA Engineer",
    offerState: "OFFER",
  },
  {
    id: 77,
    name: "Elena Jenkins",
    position: "UI/UX Designer",
    offerState: "PENDING",
  },
  {
    id: 78,
    name: "Tyler Perry",
    position: "Full Stack Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 79,
    name: "Maya Powell",
    position: "Frontend Developer",
    offerState: "REJECT",
  },
  {
    id: 80,
    name: "Brandon Long",
    position: "Backend Developer",
    offerState: "OFFER",
  },

  {
    id: 81,
    name: "Luna Patterson",
    position: "Mobile Developer",
    offerState: "PENDING",
  },
  {
    id: 82,
    name: "Kevin Hughes",
    position: "DevOps Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 83,
    name: "Ruby Flores",
    position: "Product Manager",
    offerState: "REJECT",
  },
  {
    id: 84,
    name: "Justin Washington",
    position: "Cloud Engineer",
    offerState: "OFFER",
  },
  {
    id: 85,
    name: "Alice Butler",
    position: "Data Analyst",
    offerState: "PENDING",
  },

  {
    id: 86,
    name: "Leo Simmons",
    position: "Security Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 87,
    name: "Eva Foster",
    position: "UI/UX Designer",
    offerState: "OFFER",
  },
  {
    id: 88,
    name: "Jason Gonzales",
    position: "QA Engineer",
    offerState: "REJECT",
  },
  {
    id: 89,
    name: "Autumn Bryant",
    position: "Frontend Developer",
    offerState: "PENDING",
  },
  {
    id: 90,
    name: "Aaron Alexander",
    position: "Backend Developer",
    offerState: "SHORTLIST",
  },

  {
    id: 91,
    name: "Kennedy Russell",
    position: "Data Scientist",
    offerState: "OFFER",
  },
  {
    id: 92,
    name: "Jordan Griffin",
    position: "DevOps Engineer",
    offerState: "PENDING",
  },
  {
    id: 93,
    name: "Sadie Diaz",
    position: "Full Stack Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 94,
    name: "Ian Hayes",
    position: "Mobile Developer",
    offerState: "REJECT",
  },
  {
    id: 95,
    name: "Caroline Myers",
    position: "Product Manager",
    offerState: "OFFER",
  },

  {
    id: 96,
    name: "Xavier Ford",
    position: "Cloud Engineer",
    offerState: "PENDING",
  },
  {
    id: 97,
    name: "Genesis Hamilton",
    position: "QA Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 98,
    name: "Miles Graham",
    position: "Frontend Developer",
    offerState: "REJECT",
  },
  {
    id: 99,
    name: "Ariana Sullivan",
    position: "UI/UX Designer",
    offerState: "OFFER",
  },
  {
    id: 100,
    name: "Dominic Wallace",
    position: "Backend Developer",
    offerState: "PENDING",
  },

  {
    id: 101,
    name: "Valeria Woods",
    position: "Security Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 102,
    name: "Ethan Cole",
    position: "Data Analyst",
    offerState: "OFFER",
  },
  {
    id: 103,
    name: "Melanie West",
    position: "DevOps Engineer",
    offerState: "PENDING",
  },
  {
    id: 104,
    name: "Caleb Jordan",
    position: "Full Stack Developer",
    offerState: "REJECT",
  },
  {
    id: 105,
    name: "Hazel Owens",
    position: "Frontend Developer",
    offerState: "OFFER",
  },

  {
    id: 106,
    name: "Nicholas Reynolds",
    position: "Backend Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 107,
    name: "Aurora Fisher",
    position: "Product Manager",
    offerState: "PENDING",
  },
  {
    id: 108,
    name: "Zachary Ellis",
    position: "Cloud Engineer",
    offerState: "REJECT",
  },
  {
    id: 109,
    name: "Savannah Harrison",
    position: "UI/UX Designer",
    offerState: "OFFER",
  },
  {
    id: 110,
    name: "Connor Gibson",
    position: "QA Engineer",
    offerState: "SHORTLIST",
  },

  {
    id: 111,
    name: "Brooklyn McDonald",
    position: "Mobile Developer",
    offerState: "PENDING",
  },
  {
    id: 112,
    name: "Hunter Cruz",
    position: "DevOps Engineer",
    offerState: "OFFER",
  },
  {
    id: 113,
    name: "Natalie Marshall",
    position: "Data Scientist",
    offerState: "SHORTLIST",
  },
  {
    id: 114,
    name: "Adrian Ortiz",
    position: "Security Engineer",
    offerState: "REJECT",
  },
  {
    id: 115,
    name: "Leah Gomez",
    position: "Frontend Developer",
    offerState: "OFFER",
  },

  {
    id: 116,
    name: "Jeremiah Murray",
    position: "Backend Developer",
    offerState: "PENDING",
  },
  {
    id: 117,
    name: "Everly Freeman",
    position: "Product Manager",
    offerState: "SHORTLIST",
  },
  {
    id: 118,
    name: "Angel Kim",
    position: "Cloud Engineer",
    offerState: "REJECT",
  },
  {
    id: 119,
    name: "Kinsley Webb",
    position: "UI/UX Designer",
    offerState: "OFFER",
  },
  {
    id: 120,
    name: "Tristan Simpson",
    position: "Full Stack Developer",
    offerState: "PENDING",
  },

  {
    id: 121,
    name: "Peyton Stevens",
    position: "QA Engineer",
    offerState: "SHORTLIST",
  },
  {
    id: 122,
    name: "Blake Tucker",
    position: "Mobile Developer",
    offerState: "OFFER",
  },
  {
    id: 123,
    name: "Delilah Porter",
    position: "Data Analyst",
    offerState: "PENDING",
  },
  {
    id: 124,
    name: "Grant Hunter",
    position: "DevOps Engineer",
    offerState: "REJECT",
  },
  {
    id: 125,
    name: "Rose Hicks",
    position: "Frontend Developer",
    offerState: "OFFER",
  },

  {
    id: 126,
    name: "Eric Crawford",
    position: "Backend Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 127,
    name: "Sienna Henry",
    position: "Cloud Engineer",
    offerState: "PENDING",
  },
  {
    id: 128,
    name: "Maxwell Boyd",
    position: "Security Engineer",
    offerState: "OFFER",
  },
  {
    id: 129,
    name: "Eliza Mason",
    position: "Product Manager",
    offerState: "REJECT",
  },
  {
    id: 130,
    name: "Cole Morales",
    position: "QA Engineer",
    offerState: "SHORTLIST",
  },

  {
    id: 131,
    name: "Margaret Kennedy",
    position: "UI/UX Designer",
    offerState: "OFFER",
  },
  {
    id: 132,
    name: "Dean Warren",
    position: "Full Stack Developer",
    offerState: "PENDING",
  },
  {
    id: 133,
    name: "Faith Dixon",
    position: "Frontend Developer",
    offerState: "SHORTLIST",
  },
  {
    id: 134,
    name: "Oscar Ramos",
    position: "Backend Developer",
    offerState: "REJECT",
  },
];

export const recentJobs = [
  {
    id: 1,
    jobTitle: {
      en: "UX Designer",
      ja: "UXデザイナー",
      ar: "مصمم تجربة",
      fr: "Concepteur UX",
    },
    location: "DT",
    totalApps: 122,
    trend: [12, 18, 15, 14, 16, 22, 19, 17],
  },
  {
    id: 2,
    jobTitle: {
      en: "iOS App Developer",
      ja: "iOS開発者",
      ar: "مطور iOS",
      fr: "Développeur iOS",
    },
    location: "R",
    totalApps: 34,
    trend: [8, 7, 6, 9, 11, 10, 13, 14],
  },
  {
    id: 3,
    jobTitle: {
      en: "Network Administrator",
      ja: "ネットワーク管理者",
      ar: "مسؤول الشبكة",
      fr: "Administrateur réseau",
    },
    location: "PH",
    totalApps: 45,
    trend: [10, 9, 8, 11, 12, 10, 9, 9],
  },
  {
    id: 4,
    jobTitle: {
      en: "React Developer",
      ja: "React開発者",
      ar: "مطور React",
      fr: "Développeur React",
    },
    location: "R",
    totalApps: 57,
    trend: [6, 7, 7, 10, 8, 11, 9, 10],
  },
  {
    id: 5,
    jobTitle: {
      en: "Node Developer",
      ja: "ノード開発者",
      ar: "مطور Node",
      fr: "Développeur Node",
    },
    location: "JP",
    totalApps: 38,
    trend: [15, 8, 3, 2, 1, 4, 7, 1],
  },
  {
    id: 6,
    jobTitle: {
      en: "Graphic Designer",
      ja: "グラフィックデザイナー",
      ar: "مصمم جرافيك",
      fr: "graphiste",
    },
    location: "GB",
    totalApps: 74,
    trend: [9, 10, 13, 11, 12, 14, 13, 14],
  },
  {
    id: 7,
    jobTitle: {
      en: "Python Developer",
      ja: "Python開発者",
      ar: "مطور بايثون",
      fr: "Développeur Python",
    },
    location: "R",
    totalApps: 44,
    trend: [7, 8, 7, 9, 8, 7, 7, 8],
  },
  {
    id: 8,
    jobTitle: {
      en: "Frontend Developer",
      ja: "フロントエンド開発者",
      ar: "مطور واجهات",
      fr: "Développeur Frontend",
    },
    location: "H",
    totalApps: 52,
    trend: [5, 6, 7, 6, 7, 8, 7, 9],
  },
  {
    id: 9,
    jobTitle: {
      en: "Backend Engineer",
      ja: "バックエンドエンジニア",
      ar: "مهندس خلفية",
      fr: "Ingénieur Backend",
    },
    location: "R",
    totalApps: 38,
    trend: [4, 5, 6, 6, 7, 6, 5, 6],
  },
  {
    id: 10,
    jobTitle: {
      en: "DevOps Engineer",
      ja: "DevOpsエンジニア",
      ar: "مهندس ديف أوبس",
      fr: "Ingénieur DevOps",
    },
    location: "H",
    totalApps: 27,
    trend: [3, 4, 4, 5, 6, 5, 5, 6],
  },
  {
    id: 11,
    jobTitle: {
      en: "Data Analyst",
      ja: "データアナリスト",
      ar: "محلل بيانات",
      fr: "Analyste de données",
    },
    location: "R",
    totalApps: 31,
    trend: [6, 5, 6, 7, 8, 7, 6, 7],
  },
  {
    id: 12,
    jobTitle: {
      en: "UI/UX Designer",
      ja: "UI/UXデザイナー",
      ar: "مصمم واجهات",
      fr: "Designer UI/UX",
    },
    location: "H",
    totalApps: 19,
    trend: [2, 3, 4, 4, 5, 4, 5, 6],
  },
  {
    id: 13,
    jobTitle: {
      en: "Mobile Developer",
      ja: "モバイル開発者",
      ar: "مطور الهاتف",
      fr: "Développeur Mobile",
    },
    location: "R",
    totalApps: 23,
    trend: [3, 4, 5, 6, 5, 6, 7, 7],
  },
];

export const collections = {
  insource: Array.from(
    { length: 10 },
    () => Math.floor(Math.random() * 50) + 20,
  ),
  outsource: Array.from(
    { length: 10 },
    () => Math.floor(Math.random() * 50) + 20,
  ),
};

export const activities = [
  {
    id: 0,
    date: "12 Mar",
    title: {
      en: "Community Cleanup",
      ar: "تنظيف المجتمع",
      ja: "地域清掃",
      fr: "Nettoyage communautaire",
    },
    content: {
      en: "Join neighbors to clean the local park and surrounding streets.",
      ar: "انضم إلى الجيران لتنظيف الحديقة المحلية والشوارع المحيطة.",
      ja: "近所の人たちと一緒に地域の公園と周辺の通りを清掃しましょう。",
      fr: "Rejoignez les habitants pour nettoyer le parc local et les rues voisines.",
    },
  },
  {
    id: 1,
    date: "14 Mar",
    title: {
      en: "Art Workshop",
      ar: "ورشة فنية",
      ja: "アートワークショップ",
      fr: "Atelier d’art",
    },
    content: {
      en: "A guided workshop where participants create paintings with acrylic colors.",
      ar: "ورشة إرشادية حيث يقوم المشاركون برسم لوحات باستخدام ألوان الأكريليك.",
      ja: "参加者がアクリル絵の具で作品を作るガイド付きワークショップです。",
      fr: "Un atelier guidé où les participants créent des peintures avec des couleurs acryliques.",
    },
  },
  {
    id: 2,
    date: "16 Mar",
    title: {
      en: "Book Club Meeting",
      ar: "اجتماع نادي القراءة",
      ja: "読書クラブ会議",
      fr: "Réunion du club de lecture",
    },
    content: {
      en: "Discuss this month’s selected novel and share your impressions.",
      ar: "ناقش رواية هذا الشهر المختارة وشارك انطباعاتك.",
      ja: "今月の課題小説について話し合い、感想を共有します。",
      fr: "Discutez du roman sélectionné ce mois-ci et partagez vos impressions.",
    },
  },
  {
    id: 3,
    date: "18 Mar",
    title: {
      en: "Startup Networking",
      ar: "لقاء رواد الأعمال",
      ja: "スタートアップ交流会",
      fr: "Réseautage startup",
    },
    content: {
      en: "Meet founders, developers, and investors in an informal networking session.",
      ar: "التقِ بالمؤسسين والمطورين والمستثمرين في جلسة تواصل غير رسمية.",
      ja: "創業者、開発者、投資家と気軽に交流できるネットワーキングイベントです。",
      fr: "Rencontrez des fondateurs, développeurs et investisseurs lors d’une session informelle.",
    },
  },
  {
    id: 4,
    date: "20 Mar",
    title: {
      en: "Cooking Class",
      ar: "درس الطبخ",
      ja: "料理教室",
      fr: "Cours de cuisine",
    },
    content: {
      en: "Learn how to prepare a traditional meal with fresh local ingredients.",
      ar: "تعلّم كيفية إعداد وجبة تقليدية باستخدام مكونات محلية طازجة.",
      ja: "新鮮な地元の食材を使って伝統料理を作る方法を学びます。",
      fr: "Apprenez à préparer un repas traditionnel avec des ingrédients locaux frais.",
    },
  },
  {
    id: 5,
    date: "22 Mar",
    title: {
      en: "Yoga in the Park",
      ar: "اليوغا في الحديقة",
      ja: "公園ヨガ",
      fr: "Yoga au parc",
    },
    content: {
      en: "A relaxing outdoor yoga session suitable for beginners and experienced participants.",
      ar: "جلسة يوغا مريحة في الهواء الطلق مناسبة للمبتدئين وذوي الخبرة.",
      ja: "初心者から経験者まで参加できる、屋外でのリラックスヨガです。",
      fr: "Une séance de yoga en plein air, adaptée aux débutants comme aux pratiquants confirmés.",
    },
  },
  {
    id: 6,
    date: "24 Mar",
    title: {
      en: "Tech Talk",
      ar: "محاضرة تقنية",
      ja: "技術トーク",
      fr: "Conférence tech",
    },
    content: {
      en: "Listen to a speaker explain modern web development trends and best practices.",
      ar: "استمع إلى متحدث يشرح اتجاهات تطوير الويب الحديثة وأفضل الممارسات.",
      ja: "最新のWeb開発トレンドとベストプラクティスについて講演を聞きます。",
      fr: "Écoutez un intervenant expliquer les tendances modernes du développement web.",
    },
  },
  {
    id: 7,
    date: "26 Mar",
    title: {
      en: "Charity Run",
      ar: "سباق خيري",
      ja: "チャリティーラン",
      fr: "Course caritative",
    },
    content: {
      en: "Participate in a friendly run to raise funds for local community projects.",
      ar: "شارك في سباق ودي لجمع التبرعات لمشاريع المجتمع المحلي.",
      ja: "地域プロジェクトのための資金を集めるフレンドリーなランイベントです。",
      fr: "Participez à une course conviviale pour financer des projets communautaires locaux.",
    },
  },
  {
    id: 8,
    date: "28 Mar",
    title: {
      en: "Photography Walk",
      ar: "جولة تصوير فوتوغرافي",
      ja: "フォトウォーク",
      fr: "Balade photographique",
    },
    content: {
      en: "Explore the city and capture unique architectural and street photography moments.",
      ar: "استكشف المدينة والتقط لحظات مميزة للعمارة والتصوير في الشوارع.",
      ja: "街を散策しながら建築やストリートの魅力的な瞬間を撮影します。",
      fr: "Explorez la ville et capturez des moments uniques d’architecture et de rue.",
    },
  },
  {
    id: 9,
    date: "30 Mar",
    title: {
      en: "Language Exchange",
      ar: "تبادل لغوي",
      ja: "言語交流会",
      fr: "Échange linguistique",
    },
    content: {
      en: "Practice speaking different languages with native and international participants.",
      ar: "تدرّب على التحدث بلغات مختلفة مع مشاركين محليين ودوليين.",
      ja: "ネイティブや海外参加者と一緒にさまざまな言語を練習します。",
      fr: "Pratiquez différentes langues avec des participants natifs et internationaux.",
    },
  },
  {
    id: 10,
    date: "02 Apr",
    title: {
      en: "Open Mic Night",
      ar: "ليلة الميكروفون المفتوح",
      ja: "オープンマイクナイト",
      fr: "Soirée micro ouvert",
    },
    content: {
      en: "Enjoy poetry, music, and stand-up performances from local talent.",
      ar: "استمتع بالشعر والموسيقى والعروض الكوميدية من المواهب المحلية.",
      ja: "地元の才能による詩、音楽、スタンドアップの公演を楽しめます。",
      fr: "Profitez de poésie, musique et spectacles d’humour par des talents locaux.",
    },
  },
  {
    id: 11,
    date: "04 Apr",
    title: {
      en: "Gardening Day",
      ar: "يوم البستنة",
      ja: "ガーデニングデー",
      fr: "Journée jardinage",
    },
    content: {
      en: "Plant flowers and herbs together while learning basic gardening skills.",
      ar: "ازرع الزهور والأعشاب معًا وتعلّم أساسيات البستنة.",
      ja: "花やハーブを植えながら、基本的な園芸スキルを学びます。",
      fr: "Plantez des fleurs et des herbes tout en apprenant les bases du jardinage.",
    },
  },
  {
    id: 12,
    date: "06 Apr",
    title: {
      en: "Film Screening",
      ar: "عرض فيلم",
      ja: "映画上映会",
      fr: "Projection de film",
    },
    content: {
      en: "Watch an inspiring independent film followed by a short discussion.",
      ar: "شاهد فيلمًا مستقلًا ملهمًا يتبعه نقاش قصير.",
      ja: "刺激的なインディペンデント映画を鑑賞し、その後に短い討論を行います。",
      fr: "Regardez un film indépendant inspirant suivi d’une courte discussion.",
    },
  },
  {
    id: 13,
    date: "08 Apr",
    title: {
      en: "Coding Bootcamp",
      ar: "معسكر البرمجة",
      ja: "コーディングブートキャンプ",
      fr: "Bootcamp de programmation",
    },
    content: {
      en: "A hands-on session focused on building a small web application from scratch.",
      ar: "جلسة عملية تركز على بناء تطبيق ويب صغير من الصفر.",
      ja: "小さなWebアプリをゼロから作る実践型セッションです。",
      fr: "Une session pratique consacrée à la création d’une petite application web.",
    },
  },
  {
    id: 14,
    date: "10 Apr",
    title: {
      en: "Board Games Evening",
      ar: "أمسية ألعاب الطاولة",
      ja: "ボードゲームの夕べ",
      fr: "Soirée jeux de société",
    },
    content: {
      en: "Bring friends and enjoy a fun evening of strategy and party games.",
      ar: "أحضر أصدقاءك واستمتع بأمسية ممتعة من ألعاب الاستراتيجية والمرح.",
      ja: "友人と一緒に、戦略ゲームやパーティーゲームを楽しむ夜です。",
      fr: "Venez avec des amis pour une soirée amusante de jeux de stratégie et d’ambiance.",
    },
  },
  {
    id: 15,
    date: "12 Apr",
    title: {
      en: "Beach Volunteer Day",
      ar: "يوم تطوعي على الشاطئ",
      ja: "ビーチボランティアデー",
      fr: "Journée bénévole à la plage",
    },
    content: {
      en: "Help clean the beach and protect marine life through a local volunteer initiative.",
      ar: "ساعد في تنظيف الشاطئ وحماية الحياة البحرية من خلال مبادرة تطوعية محلية.",
      ja: "地元のボランティア活動を通して、ビーチ清掃と海洋生物の保護に参加します。",
      fr: "Aidez à nettoyer la plage et à protéger la vie marine grâce à une initiative locale.",
    },
  },
  {
    id: 16,
    date: "14 Apr",
    title: {
      en: "Cultural Festival",
      ar: "مهرجان ثقافي",
      ja: "文化フェスティバル",
      fr: "Festival culturel",
    },
    content: {
      en: "Celebrate diversity with music, food, crafts, and performances from different cultures.",
      ar: "احتفل بالتنوع من خلال الموسيقى والطعام والحرف والعروض من ثقافات مختلفة.",
      ja: "音楽、料理、工芸、パフォーマンスを通して多様な文化を祝います。",
      fr: "Célébrez la diversité avec de la musique, de la cuisine, de l’artisanat et des spectacles.",
    },
  },
];
